/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_window_gestion_troupeau_mb (void)
{
  GtkWidget *window_gestion_troupeau_mb;
  GtkWidget *fixed1;
  GtkWidget *NotebookGestionDesTroupeaux;
  GtkWidget *fixed2;
  GtkWidget *entry_identifiant_1_mb;
  GtkObject *spin_button_etat_1_mb_adj;
  GtkWidget *spin_button_etat_1_mb;
  GtkWidget *label_type_1_mb;
  GtkWidget *label_sexe_1_mb;
  GtkWidget *label_etat_1_mb;
  GtkWidget *label_date_1_mb;
  GtkWidget *calendar_mb1;
  GtkWidget *combo_sexe_1_mb;
  GtkWidget *button_ajouter_mb;
  GtkWidget *alignment1;
  GtkWidget *hbox1;
  GtkWidget *image1;
  GtkWidget *label8;
  GtkWidget *combo_type_1_mb;
  GtkWidget *label_Identifiant_1_mb;
  GtkWidget *label3;
  GtkWidget *label4;
  GtkWidget *label5;
  GtkWidget *label_echec_1_mb;
  GtkWidget *label_sucess_1_mb;
  GtkWidget *label_ajouter_animal_mb;
  GtkWidget *fixed4;
  GtkObject *spin_button_etat_2_mb_adj;
  GtkWidget *spin_button_etat_2_mb;
  GtkWidget *button_supprimer_mb;
  GtkWidget *alignment2;
  GtkWidget *hbox2;
  GtkWidget *image2;
  GtkWidget *label9;
  GtkWidget *label_sexe_2_mb;
  GtkWidget *label_etat_2_mb;
  GtkWidget *label_date_2_mb;
  GtkWidget *combo_sexe_2_mb;
  GtkWidget *entry_identifiant_2_mb;
  GtkWidget *label_type_2_mb;
  GtkWidget *label_identifiant_2_mb;
  GtkWidget *calendar_mb2;
  GtkWidget *scrolled_window_1_mb;
  GtkWidget *viewport1;
  GtkWidget *fixed6;
  GtkWidget *treeview_1_mb;
  GtkWidget *label12;
  GtkWidget *label13;
  GtkWidget *label14;
  GtkWidget *button_modifier_mb;
  GtkWidget *label_echec_2_mb;
  GtkWidget *label_sucess_2_mb;
  GtkWidget *label19;
  GtkWidget *combo_type_2_mb;
  GtkWidget *label_afficher_supprimer_animal_mb;
  GtkWidget *fixed5;
  GtkWidget *entry_identifiant_3_mb;
  GtkWidget *scrolled_window_2_mb;
  GtkWidget *viewport2;
  GtkWidget *fixed8;
  GtkWidget *treeview_2_mb;
  GtkWidget *button_chercher_mb;
  GtkWidget *alignment3;
  GtkWidget *hbox3;
  GtkWidget *image3;
  GtkWidget *label11;
  GtkWidget *label_Identifiant_3_mb;
  GtkWidget *label_chercher_animal_mb;
  GtkWidget *fixed7;
  GtkWidget *label_nombre_brebis_mb;
  GtkWidget *label_nombre_veau_mb;
  GtkWidget *label_nombre_veau_output_mb;
  GtkWidget *label_nombre_brebis_output_mb;
  GtkWidget *label_nombre_mb;

  window_gestion_troupeau_mb = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (window_gestion_troupeau_mb, 1200, 700);
  gtk_window_set_title (GTK_WINDOW (window_gestion_troupeau_mb), _("Gestion des troupeaux"));

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (window_gestion_troupeau_mb), fixed1);

  NotebookGestionDesTroupeaux = gtk_notebook_new ();
  gtk_widget_show (NotebookGestionDesTroupeaux);
  gtk_fixed_put (GTK_FIXED (fixed1), NotebookGestionDesTroupeaux, 0, 0);
  gtk_widget_set_size_request (NotebookGestionDesTroupeaux, 352, 16);

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (NotebookGestionDesTroupeaux), fixed2);

  entry_identifiant_1_mb = gtk_entry_new ();
  gtk_widget_show (entry_identifiant_1_mb);
  gtk_fixed_put (GTK_FIXED (fixed2), entry_identifiant_1_mb, 296, 64);
  gtk_widget_set_size_request (entry_identifiant_1_mb, 168, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_identifiant_1_mb), 8226);

  spin_button_etat_1_mb_adj = gtk_adjustment_new (1, 0, 1, 1, 10, 10);
  spin_button_etat_1_mb = gtk_spin_button_new (GTK_ADJUSTMENT (spin_button_etat_1_mb_adj), 1, 0);
  gtk_widget_show (spin_button_etat_1_mb);
  gtk_fixed_put (GTK_FIXED (fixed2), spin_button_etat_1_mb, 296, 184);
  gtk_widget_set_size_request (spin_button_etat_1_mb, 168, 27);

  label_type_1_mb = gtk_label_new (_("Type"));
  gtk_widget_show (label_type_1_mb);
  gtk_fixed_put (GTK_FIXED (fixed2), label_type_1_mb, 120, 104);
  gtk_widget_set_size_request (label_type_1_mb, 128, 25);

  label_sexe_1_mb = gtk_label_new (_("Sexe"));
  gtk_widget_show (label_sexe_1_mb);
  gtk_fixed_put (GTK_FIXED (fixed2), label_sexe_1_mb, 120, 144);
  gtk_widget_set_size_request (label_sexe_1_mb, 128, 25);

  label_etat_1_mb = gtk_label_new (_("Etat"));
  gtk_widget_show (label_etat_1_mb);
  gtk_fixed_put (GTK_FIXED (fixed2), label_etat_1_mb, 120, 184);
  gtk_widget_set_size_request (label_etat_1_mb, 120, 25);

  label_date_1_mb = gtk_label_new (_("Date de naissance"));
  gtk_widget_show (label_date_1_mb);
  gtk_fixed_put (GTK_FIXED (fixed2), label_date_1_mb, 160, 224);
  gtk_widget_set_size_request (label_date_1_mb, 136, 24);

  calendar_mb1 = gtk_calendar_new ();
  gtk_widget_show (calendar_mb1);
  gtk_fixed_put (GTK_FIXED (fixed2), calendar_mb1, 296, 224);
  gtk_widget_set_size_request (calendar_mb1, 168, 192);
  gtk_calendar_display_options (GTK_CALENDAR (calendar_mb1),
                                GTK_CALENDAR_SHOW_HEADING
                                | GTK_CALENDAR_SHOW_DAY_NAMES);

  combo_sexe_1_mb = gtk_combo_box_entry_new_text ();
  gtk_widget_show (combo_sexe_1_mb);
  gtk_fixed_put (GTK_FIXED (fixed2), combo_sexe_1_mb, 296, 144);
  gtk_widget_set_size_request (combo_sexe_1_mb, 168, 29);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combo_sexe_1_mb), _("Male"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combo_sexe_1_mb), _("Femelle"));

  button_ajouter_mb = gtk_button_new ();
  gtk_widget_show (button_ajouter_mb);
  gtk_fixed_put (GTK_FIXED (fixed2), button_ajouter_mb, 336, 472);
  gtk_widget_set_size_request (button_ajouter_mb, 120, 37);

  alignment1 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (button_ajouter_mb), alignment1);

  hbox1 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox1);
  gtk_container_add (GTK_CONTAINER (alignment1), hbox1);

  image1 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image1);
  gtk_box_pack_start (GTK_BOX (hbox1), image1, FALSE, FALSE, 0);

  label8 = gtk_label_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (label8);
  gtk_box_pack_start (GTK_BOX (hbox1), label8, FALSE, FALSE, 0);

  combo_type_1_mb = gtk_combo_box_entry_new_text ();
  gtk_widget_show (combo_type_1_mb);
  gtk_fixed_put (GTK_FIXED (fixed2), combo_type_1_mb, 296, 104);
  gtk_widget_set_size_request (combo_type_1_mb, 168, 29);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combo_type_1_mb), _("Veau"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combo_type_1_mb), _("Brebis"));

  label_Identifiant_1_mb = gtk_label_new (_("Identifiant"));
  gtk_widget_show (label_Identifiant_1_mb);
  gtk_fixed_put (GTK_FIXED (fixed2), label_Identifiant_1_mb, 136, 64);
  gtk_widget_set_size_request (label_Identifiant_1_mb, 128, 24);

  label3 = gtk_label_new (_("<span foreground=\"red\" ><b>Veuillez saisir un identifiant</b></span>"));
  gtk_fixed_put (GTK_FIXED (fixed2), label3, 448, 48);
  gtk_widget_set_size_request (label3, 250, 64);
  gtk_label_set_use_markup (GTK_LABEL (label3), TRUE);
  gtk_misc_set_alignment (GTK_MISC (label3), 0.49, 0.5);

  label4 = gtk_label_new (_("<span foreground=\"red\" ><b>Veuillez saisir un type</b></span>"));
  gtk_fixed_put (GTK_FIXED (fixed2), label4, 424, 88);
  gtk_widget_set_size_request (label4, 250, 64);
  gtk_label_set_use_markup (GTK_LABEL (label4), TRUE);
  gtk_misc_set_alignment (GTK_MISC (label4), 0.49, 0.5);

  label5 = gtk_label_new (_("<span foreground=\"red\" ><b>Veuillez saisir un sexe</b></span>"));
  gtk_fixed_put (GTK_FIXED (fixed2), label5, 424, 128);
  gtk_widget_set_size_request (label5, 250, 64);
  gtk_label_set_use_markup (GTK_LABEL (label5), TRUE);
  gtk_misc_set_alignment (GTK_MISC (label5), 0.49, 0.5);

  label_echec_1_mb = gtk_label_new (_("<span foreground=\"red\" ><b>L'animal existe deja !</b></span>"));
  gtk_fixed_put (GTK_FIXED (fixed2), label_echec_1_mb, 8, 464);
  gtk_widget_set_size_request (label_echec_1_mb, 250, 64);
  gtk_label_set_use_markup (GTK_LABEL (label_echec_1_mb), TRUE);
  gtk_misc_set_alignment (GTK_MISC (label_echec_1_mb), 0.49, 0.5);

  label_sucess_1_mb = gtk_label_new (_("<span foreground=\"green\" ><b>L'animal a \303\251t\303\251 ajout\303\251 avec succ\303\250s !</b></span>"));
  gtk_fixed_put (GTK_FIXED (fixed2), label_sucess_1_mb, 8, 464);
  gtk_widget_set_size_request (label_sucess_1_mb, 250, 64);
  gtk_label_set_use_markup (GTK_LABEL (label_sucess_1_mb), TRUE);
  gtk_misc_set_alignment (GTK_MISC (label_sucess_1_mb), 0.49, 0.5);

  label_ajouter_animal_mb = gtk_label_new (_("Ajouter animal"));
  gtk_widget_show (label_ajouter_animal_mb);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (NotebookGestionDesTroupeaux), gtk_notebook_get_nth_page (GTK_NOTEBOOK (NotebookGestionDesTroupeaux), 0), label_ajouter_animal_mb);

  fixed4 = gtk_fixed_new ();
  gtk_widget_show (fixed4);
  gtk_container_add (GTK_CONTAINER (NotebookGestionDesTroupeaux), fixed4);

  spin_button_etat_2_mb_adj = gtk_adjustment_new (1, 0, 1, 1, 10, 10);
  spin_button_etat_2_mb = gtk_spin_button_new (GTK_ADJUSTMENT (spin_button_etat_2_mb_adj), 1, 0);
  gtk_widget_show (spin_button_etat_2_mb);
  gtk_fixed_put (GTK_FIXED (fixed4), spin_button_etat_2_mb, 680, 136);
  gtk_widget_set_size_request (spin_button_etat_2_mb, 162, 27);

  button_supprimer_mb = gtk_button_new ();
  gtk_widget_show (button_supprimer_mb);
  gtk_fixed_put (GTK_FIXED (fixed4), button_supprimer_mb, 184, 496);
  gtk_widget_set_size_request (button_supprimer_mb, 120, 37);

  alignment2 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (button_supprimer_mb), alignment2);

  hbox2 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox2);
  gtk_container_add (GTK_CONTAINER (alignment2), hbox2);

  image2 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image2);
  gtk_box_pack_start (GTK_BOX (hbox2), image2, FALSE, FALSE, 0);

  label9 = gtk_label_new_with_mnemonic (_("Supprimer"));
  gtk_widget_show (label9);
  gtk_box_pack_start (GTK_BOX (hbox2), label9, FALSE, FALSE, 0);

  label_sexe_2_mb = gtk_label_new (_("Sexe"));
  gtk_widget_show (label_sexe_2_mb);
  gtk_fixed_put (GTK_FIXED (fixed4), label_sexe_2_mb, 536, 96);
  gtk_widget_set_size_request (label_sexe_2_mb, 128, 25);

  label_etat_2_mb = gtk_label_new (_("Etat"));
  gtk_widget_show (label_etat_2_mb);
  gtk_fixed_put (GTK_FIXED (fixed4), label_etat_2_mb, 536, 136);
  gtk_widget_set_size_request (label_etat_2_mb, 120, 25);

  label_date_2_mb = gtk_label_new (_("Date de naissance"));
  gtk_widget_show (label_date_2_mb);
  gtk_fixed_put (GTK_FIXED (fixed4), label_date_2_mb, 488, 176);
  gtk_widget_set_size_request (label_date_2_mb, 136, 24);

  combo_sexe_2_mb = gtk_combo_box_entry_new_text ();
  gtk_widget_show (combo_sexe_2_mb);
  gtk_fixed_put (GTK_FIXED (fixed4), combo_sexe_2_mb, 680, 96);
  gtk_widget_set_size_request (combo_sexe_2_mb, 162, 29);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combo_sexe_2_mb), _("Male"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combo_sexe_2_mb), _("Femelle"));

  entry_identifiant_2_mb = gtk_entry_new ();
  gtk_widget_show (entry_identifiant_2_mb);
  gtk_fixed_put (GTK_FIXED (fixed4), entry_identifiant_2_mb, 680, 16);
  gtk_widget_set_size_request (entry_identifiant_2_mb, 168, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_identifiant_2_mb), 8226);

  label_type_2_mb = gtk_label_new (_("Type"));
  gtk_widget_show (label_type_2_mb);
  gtk_fixed_put (GTK_FIXED (fixed4), label_type_2_mb, 536, 56);
  gtk_widget_set_size_request (label_type_2_mb, 128, 25);

  label_identifiant_2_mb = gtk_label_new (_("Identifiant"));
  gtk_widget_show (label_identifiant_2_mb);
  gtk_fixed_put (GTK_FIXED (fixed4), label_identifiant_2_mb, 520, 16);
  gtk_widget_set_size_request (label_identifiant_2_mb, 128, 24);

  calendar_mb2 = gtk_calendar_new ();
  gtk_widget_show (calendar_mb2);
  gtk_fixed_put (GTK_FIXED (fixed4), calendar_mb2, 680, 184);
  gtk_widget_set_size_request (calendar_mb2, 168, 192);
  gtk_calendar_display_options (GTK_CALENDAR (calendar_mb2),
                                GTK_CALENDAR_SHOW_HEADING
                                | GTK_CALENDAR_SHOW_DAY_NAMES);

  scrolled_window_1_mb = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolled_window_1_mb);
  gtk_fixed_put (GTK_FIXED (fixed4), scrolled_window_1_mb, 8, 8);
  gtk_widget_set_size_request (scrolled_window_1_mb, 480, 480);

  viewport1 = gtk_viewport_new (NULL, NULL);
  gtk_widget_show (viewport1);
  gtk_container_add (GTK_CONTAINER (scrolled_window_1_mb), viewport1);

  fixed6 = gtk_fixed_new ();
  gtk_widget_show (fixed6);
  gtk_container_add (GTK_CONTAINER (viewport1), fixed6);

  treeview_1_mb = gtk_tree_view_new ();
  gtk_widget_show (treeview_1_mb);
  gtk_fixed_put (GTK_FIXED (fixed6), treeview_1_mb, 0, 0);
  gtk_widget_set_size_request (treeview_1_mb, 648, 472);

  label12 = gtk_label_new (_("<span foreground=\"red\" ><b>Veuillez saisir un identifiant</b></span>"));
  gtk_fixed_put (GTK_FIXED (fixed4), label12, 856, 0);
  gtk_widget_set_size_request (label12, 250, 64);
  gtk_label_set_use_markup (GTK_LABEL (label12), TRUE);
  gtk_misc_set_alignment (GTK_MISC (label12), 0.49, 0.5);

  label13 = gtk_label_new (_("<span foreground=\"red\" ><b>Veuillez saisir un type</b></span>"));
  gtk_fixed_put (GTK_FIXED (fixed4), label13, 840, 40);
  gtk_widget_set_size_request (label13, 250, 64);
  gtk_label_set_use_markup (GTK_LABEL (label13), TRUE);
  gtk_misc_set_alignment (GTK_MISC (label13), 0.49, 0.5);

  label14 = gtk_label_new (_("<span foreground=\"red\" ><b>Veuillez saisir un sexe</b></span>"));
  gtk_fixed_put (GTK_FIXED (fixed4), label14, 840, 80);
  gtk_widget_set_size_request (label14, 250, 64);
  gtk_label_set_use_markup (GTK_LABEL (label14), TRUE);
  gtk_misc_set_alignment (GTK_MISC (label14), 0.49, 0.5);

  button_modifier_mb = gtk_button_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (button_modifier_mb);
  gtk_fixed_put (GTK_FIXED (fixed4), button_modifier_mb, 800, 416);
  gtk_widget_set_size_request (button_modifier_mb, 120, 37);

  label_echec_2_mb = gtk_label_new (_("<span foreground=\"red\" ><b>L'animal existe deja !</b></span>"));
  gtk_fixed_put (GTK_FIXED (fixed4), label_echec_2_mb, 512, 424);
  gtk_widget_set_size_request (label_echec_2_mb, 250, 64);
  gtk_label_set_use_markup (GTK_LABEL (label_echec_2_mb), TRUE);
  gtk_misc_set_alignment (GTK_MISC (label_echec_2_mb), 0.49, 0.5);

  label_sucess_2_mb = gtk_label_new (_("<span foreground=\"green\" ><b>L'animal a \303\251t\303\251 modifi\303\251 avec succ\303\250s !</b></span>"));
  gtk_fixed_put (GTK_FIXED (fixed4), label_sucess_2_mb, 512, 424);
  gtk_widget_set_size_request (label_sucess_2_mb, 250, 64);
  gtk_label_set_use_markup (GTK_LABEL (label_sucess_2_mb), TRUE);
  gtk_misc_set_alignment (GTK_MISC (label_sucess_2_mb), 0.49, 0.5);

  label19 = gtk_label_new (_("<span foreground=\"red\" ><b>Veuillez selectionner une ligne \303\240 modifier</b></span>"));
  gtk_fixed_put (GTK_FIXED (fixed4), label19, 800, 480);
  gtk_widget_set_size_request (label19, 310, 64);
  gtk_label_set_use_markup (GTK_LABEL (label19), TRUE);
  gtk_misc_set_alignment (GTK_MISC (label19), 0.49, 0.5);

  combo_type_2_mb = gtk_combo_box_entry_new_text ();
  gtk_widget_show (combo_type_2_mb);
  gtk_fixed_put (GTK_FIXED (fixed4), combo_type_2_mb, 680, 56);
  gtk_widget_set_size_request (combo_type_2_mb, 162, 29);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combo_type_2_mb), _("Veau"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combo_type_2_mb), _("Brebis"));

  label_afficher_supprimer_animal_mb = gtk_label_new (_("Afficher/Supprimer animal"));
  gtk_widget_show (label_afficher_supprimer_animal_mb);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (NotebookGestionDesTroupeaux), gtk_notebook_get_nth_page (GTK_NOTEBOOK (NotebookGestionDesTroupeaux), 1), label_afficher_supprimer_animal_mb);

  fixed5 = gtk_fixed_new ();
  gtk_widget_show (fixed5);
  gtk_container_add (GTK_CONTAINER (NotebookGestionDesTroupeaux), fixed5);

  entry_identifiant_3_mb = gtk_entry_new ();
  gtk_widget_show (entry_identifiant_3_mb);
  gtk_fixed_put (GTK_FIXED (fixed5), entry_identifiant_3_mb, 632, 104);
  gtk_widget_set_size_request (entry_identifiant_3_mb, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_identifiant_3_mb), 8226);

  scrolled_window_2_mb = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolled_window_2_mb);
  gtk_fixed_put (GTK_FIXED (fixed5), scrolled_window_2_mb, 8, 24);
  gtk_widget_set_size_request (scrolled_window_2_mb, 424, 312);

  viewport2 = gtk_viewport_new (NULL, NULL);
  gtk_widget_show (viewport2);
  gtk_container_add (GTK_CONTAINER (scrolled_window_2_mb), viewport2);

  fixed8 = gtk_fixed_new ();
  gtk_widget_show (fixed8);
  gtk_container_add (GTK_CONTAINER (viewport2), fixed8);

  treeview_2_mb = gtk_tree_view_new ();
  gtk_widget_show (treeview_2_mb);
  gtk_fixed_put (GTK_FIXED (fixed8), treeview_2_mb, 0, 0);
  gtk_widget_set_size_request (treeview_2_mb, 428, 328);

  button_chercher_mb = gtk_button_new ();
  gtk_widget_show (button_chercher_mb);
  gtk_fixed_put (GTK_FIXED (fixed5), button_chercher_mb, 600, 160);
  gtk_widget_set_size_request (button_chercher_mb, 120, 37);

  alignment3 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment3);
  gtk_container_add (GTK_CONTAINER (button_chercher_mb), alignment3);

  hbox3 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox3);
  gtk_container_add (GTK_CONTAINER (alignment3), hbox3);

  image3 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image3);
  gtk_box_pack_start (GTK_BOX (hbox3), image3, FALSE, FALSE, 0);

  label11 = gtk_label_new_with_mnemonic (_("Chercher"));
  gtk_widget_show (label11);
  gtk_box_pack_start (GTK_BOX (hbox3), label11, FALSE, FALSE, 0);

  label_Identifiant_3_mb = gtk_label_new (_("Identifiant"));
  gtk_widget_show (label_Identifiant_3_mb);
  gtk_fixed_put (GTK_FIXED (fixed5), label_Identifiant_3_mb, 496, 104);
  gtk_widget_set_size_request (label_Identifiant_3_mb, 128, 24);

  label_chercher_animal_mb = gtk_label_new (_("Chercher animal"));
  gtk_widget_show (label_chercher_animal_mb);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (NotebookGestionDesTroupeaux), gtk_notebook_get_nth_page (GTK_NOTEBOOK (NotebookGestionDesTroupeaux), 2), label_chercher_animal_mb);

  fixed7 = gtk_fixed_new ();
  gtk_widget_show (fixed7);
  gtk_container_add (GTK_CONTAINER (NotebookGestionDesTroupeaux), fixed7);

  label_nombre_brebis_mb = gtk_label_new (_("Nombre brebis"));
  gtk_widget_show (label_nombre_brebis_mb);
  gtk_fixed_put (GTK_FIXED (fixed7), label_nombre_brebis_mb, 232, 184);
  gtk_widget_set_size_request (label_nombre_brebis_mb, 150, 17);

  label_nombre_veau_mb = gtk_label_new (_("Nombre veaux"));
  gtk_widget_show (label_nombre_veau_mb);
  gtk_fixed_put (GTK_FIXED (fixed7), label_nombre_veau_mb, 232, 136);
  gtk_widget_set_size_request (label_nombre_veau_mb, 150, 17);

  label_nombre_veau_output_mb = gtk_label_new (_("\n"));
  gtk_widget_show (label_nombre_veau_output_mb);
  gtk_fixed_put (GTK_FIXED (fixed7), label_nombre_veau_output_mb, 376, 136);
  gtk_widget_set_size_request (label_nombre_veau_output_mb, 49, 17);

  label_nombre_brebis_output_mb = gtk_label_new (_("\n"));
  gtk_widget_show (label_nombre_brebis_output_mb);
  gtk_fixed_put (GTK_FIXED (fixed7), label_nombre_brebis_output_mb, 376, 184);
  gtk_widget_set_size_request (label_nombre_brebis_output_mb, 49, 17);

  label_nombre_mb = gtk_label_new (_("Nombre Brebis/Veaux"));
  gtk_widget_show (label_nombre_mb);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (NotebookGestionDesTroupeaux), gtk_notebook_get_nth_page (GTK_NOTEBOOK (NotebookGestionDesTroupeaux), 3), label_nombre_mb);

  g_signal_connect ((gpointer) window_gestion_troupeau_mb, "destroy",
                    G_CALLBACK (on_window_gestion_troupeau_mb_destroy),
                    NULL);
  g_signal_connect ((gpointer) button_ajouter_mb, "clicked",
                    G_CALLBACK (on_button_ajouter_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_supprimer_mb, "clicked",
                    G_CALLBACK (on_button_supprimer_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_modifier_mb, "clicked",
                    G_CALLBACK (on_button_modifier_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_chercher_mb, "clicked",
                    G_CALLBACK (on_button_chercher_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window_gestion_troupeau_mb, window_gestion_troupeau_mb, "window_gestion_troupeau_mb");
  GLADE_HOOKUP_OBJECT (window_gestion_troupeau_mb, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (window_gestion_troupeau_mb, NotebookGestionDesTroupeaux, "NotebookGestionDesTroupeaux");
  GLADE_HOOKUP_OBJECT (window_gestion_troupeau_mb, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (window_gestion_troupeau_mb, entry_identifiant_1_mb, "entry_identifiant_1_mb");
  GLADE_HOOKUP_OBJECT (window_gestion_troupeau_mb, spin_button_etat_1_mb, "spin_button_etat_1_mb");
  GLADE_HOOKUP_OBJECT (window_gestion_troupeau_mb, label_type_1_mb, "label_type_1_mb");
  GLADE_HOOKUP_OBJECT (window_gestion_troupeau_mb, label_sexe_1_mb, "label_sexe_1_mb");
  GLADE_HOOKUP_OBJECT (window_gestion_troupeau_mb, label_etat_1_mb, "label_etat_1_mb");
  GLADE_HOOKUP_OBJECT (window_gestion_troupeau_mb, label_date_1_mb, "label_date_1_mb");
  GLADE_HOOKUP_OBJECT (window_gestion_troupeau_mb, calendar_mb1, "calendar_mb1");
  GLADE_HOOKUP_OBJECT (window_gestion_troupeau_mb, combo_sexe_1_mb, "combo_sexe_1_mb");
  GLADE_HOOKUP_OBJECT (window_gestion_troupeau_mb, button_ajouter_mb, "button_ajouter_mb");
  GLADE_HOOKUP_OBJECT (window_gestion_troupeau_mb, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (window_gestion_troupeau_mb, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (window_gestion_troupeau_mb, image1, "image1");
  GLADE_HOOKUP_OBJECT (window_gestion_troupeau_mb, label8, "label8");
  GLADE_HOOKUP_OBJECT (window_gestion_troupeau_mb, combo_type_1_mb, "combo_type_1_mb");
  GLADE_HOOKUP_OBJECT (window_gestion_troupeau_mb, label_Identifiant_1_mb, "label_Identifiant_1_mb");
  GLADE_HOOKUP_OBJECT (window_gestion_troupeau_mb, label3, "label3");
  GLADE_HOOKUP_OBJECT (window_gestion_troupeau_mb, label4, "label4");
  GLADE_HOOKUP_OBJECT (window_gestion_troupeau_mb, label5, "label5");
  GLADE_HOOKUP_OBJECT (window_gestion_troupeau_mb, label_echec_1_mb, "label_echec_1_mb");
  GLADE_HOOKUP_OBJECT (window_gestion_troupeau_mb, label_sucess_1_mb, "label_sucess_1_mb");
  GLADE_HOOKUP_OBJECT (window_gestion_troupeau_mb, label_ajouter_animal_mb, "label_ajouter_animal_mb");
  GLADE_HOOKUP_OBJECT (window_gestion_troupeau_mb, fixed4, "fixed4");
  GLADE_HOOKUP_OBJECT (window_gestion_troupeau_mb, spin_button_etat_2_mb, "spin_button_etat_2_mb");
  GLADE_HOOKUP_OBJECT (window_gestion_troupeau_mb, button_supprimer_mb, "button_supprimer_mb");
  GLADE_HOOKUP_OBJECT (window_gestion_troupeau_mb, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (window_gestion_troupeau_mb, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (window_gestion_troupeau_mb, image2, "image2");
  GLADE_HOOKUP_OBJECT (window_gestion_troupeau_mb, label9, "label9");
  GLADE_HOOKUP_OBJECT (window_gestion_troupeau_mb, label_sexe_2_mb, "label_sexe_2_mb");
  GLADE_HOOKUP_OBJECT (window_gestion_troupeau_mb, label_etat_2_mb, "label_etat_2_mb");
  GLADE_HOOKUP_OBJECT (window_gestion_troupeau_mb, label_date_2_mb, "label_date_2_mb");
  GLADE_HOOKUP_OBJECT (window_gestion_troupeau_mb, combo_sexe_2_mb, "combo_sexe_2_mb");
  GLADE_HOOKUP_OBJECT (window_gestion_troupeau_mb, entry_identifiant_2_mb, "entry_identifiant_2_mb");
  GLADE_HOOKUP_OBJECT (window_gestion_troupeau_mb, label_type_2_mb, "label_type_2_mb");
  GLADE_HOOKUP_OBJECT (window_gestion_troupeau_mb, label_identifiant_2_mb, "label_identifiant_2_mb");
  GLADE_HOOKUP_OBJECT (window_gestion_troupeau_mb, calendar_mb2, "calendar_mb2");
  GLADE_HOOKUP_OBJECT (window_gestion_troupeau_mb, scrolled_window_1_mb, "scrolled_window_1_mb");
  GLADE_HOOKUP_OBJECT (window_gestion_troupeau_mb, viewport1, "viewport1");
  GLADE_HOOKUP_OBJECT (window_gestion_troupeau_mb, fixed6, "fixed6");
  GLADE_HOOKUP_OBJECT (window_gestion_troupeau_mb, treeview_1_mb, "treeview_1_mb");
  GLADE_HOOKUP_OBJECT (window_gestion_troupeau_mb, label12, "label12");
  GLADE_HOOKUP_OBJECT (window_gestion_troupeau_mb, label13, "label13");
  GLADE_HOOKUP_OBJECT (window_gestion_troupeau_mb, label14, "label14");
  GLADE_HOOKUP_OBJECT (window_gestion_troupeau_mb, button_modifier_mb, "button_modifier_mb");
  GLADE_HOOKUP_OBJECT (window_gestion_troupeau_mb, label_echec_2_mb, "label_echec_2_mb");
  GLADE_HOOKUP_OBJECT (window_gestion_troupeau_mb, label_sucess_2_mb, "label_sucess_2_mb");
  GLADE_HOOKUP_OBJECT (window_gestion_troupeau_mb, label19, "label19");
  GLADE_HOOKUP_OBJECT (window_gestion_troupeau_mb, combo_type_2_mb, "combo_type_2_mb");
  GLADE_HOOKUP_OBJECT (window_gestion_troupeau_mb, label_afficher_supprimer_animal_mb, "label_afficher_supprimer_animal_mb");
  GLADE_HOOKUP_OBJECT (window_gestion_troupeau_mb, fixed5, "fixed5");
  GLADE_HOOKUP_OBJECT (window_gestion_troupeau_mb, entry_identifiant_3_mb, "entry_identifiant_3_mb");
  GLADE_HOOKUP_OBJECT (window_gestion_troupeau_mb, scrolled_window_2_mb, "scrolled_window_2_mb");
  GLADE_HOOKUP_OBJECT (window_gestion_troupeau_mb, viewport2, "viewport2");
  GLADE_HOOKUP_OBJECT (window_gestion_troupeau_mb, fixed8, "fixed8");
  GLADE_HOOKUP_OBJECT (window_gestion_troupeau_mb, treeview_2_mb, "treeview_2_mb");
  GLADE_HOOKUP_OBJECT (window_gestion_troupeau_mb, button_chercher_mb, "button_chercher_mb");
  GLADE_HOOKUP_OBJECT (window_gestion_troupeau_mb, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (window_gestion_troupeau_mb, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (window_gestion_troupeau_mb, image3, "image3");
  GLADE_HOOKUP_OBJECT (window_gestion_troupeau_mb, label11, "label11");
  GLADE_HOOKUP_OBJECT (window_gestion_troupeau_mb, label_Identifiant_3_mb, "label_Identifiant_3_mb");
  GLADE_HOOKUP_OBJECT (window_gestion_troupeau_mb, label_chercher_animal_mb, "label_chercher_animal_mb");
  GLADE_HOOKUP_OBJECT (window_gestion_troupeau_mb, fixed7, "fixed7");
  GLADE_HOOKUP_OBJECT (window_gestion_troupeau_mb, label_nombre_brebis_mb, "label_nombre_brebis_mb");
  GLADE_HOOKUP_OBJECT (window_gestion_troupeau_mb, label_nombre_veau_mb, "label_nombre_veau_mb");
  GLADE_HOOKUP_OBJECT (window_gestion_troupeau_mb, label_nombre_veau_output_mb, "label_nombre_veau_output_mb");
  GLADE_HOOKUP_OBJECT (window_gestion_troupeau_mb, label_nombre_brebis_output_mb, "label_nombre_brebis_output_mb");
  GLADE_HOOKUP_OBJECT (window_gestion_troupeau_mb, label_nombre_mb, "label_nombre_mb");

  gtk_widget_grab_focus (treeview_1_mb);
  return window_gestion_troupeau_mb;
}

GtkWidget*
create_window_mb (void)
{
  GtkWidget *window_mb;
  GtkWidget *fixed9;
  GtkWidget *button_gestion_mb;

  window_mb = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (window_mb, 350, 350);
  gtk_window_set_title (GTK_WINDOW (window_mb), _("Accueil"));

  fixed9 = gtk_fixed_new ();
  gtk_widget_show (fixed9);
  gtk_container_add (GTK_CONTAINER (window_mb), fixed9);

  button_gestion_mb = gtk_button_new_with_mnemonic (_("Gestion troupeaux"));
  gtk_widget_show (button_gestion_mb);
  gtk_fixed_put (GTK_FIXED (fixed9), button_gestion_mb, 88, 104);
  gtk_widget_set_size_request (button_gestion_mb, 224, 77);

  g_signal_connect ((gpointer) button_gestion_mb, "clicked",
                    G_CALLBACK (on_button_gestion_mb_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window_mb, window_mb, "window_mb");
  GLADE_HOOKUP_OBJECT (window_mb, fixed9, "fixed9");
  GLADE_HOOKUP_OBJECT (window_mb, button_gestion_mb, "button_gestion_mb");

  gtk_widget_grab_default (fixed9);
  return window_mb;
}

