/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <gtk/gtk.h>
#include<stdio.h>
#include<stdlib.h>
#include<string.h>
#include "interface.h"
#include "support.h"
#include"tree.h"
#include"troupeau.h"

int
main (int argc, char *argv[])
{
  GtkWidget *window_gestion_troupeau_mb;
  char nombreBrebis[30];
  char nombreVeaux[30];
  int nbBrebis,nbVeaux;

#ifdef ENABLE_NLS
  bindtextdomain (GETTEXT_PACKAGE, PACKAGE_LOCALE_DIR);
  bind_textdomain_codeset (GETTEXT_PACKAGE, "UTF-8");
  textdomain (GETTEXT_PACKAGE);
#endif

  gtk_set_locale ();
  gtk_init (&argc, &argv);

  add_pixmap_directory (PACKAGE_DATA_DIR "/" PACKAGE "/pixmaps");

  /*
   * The following code was added by Glade to create one of each component
   * (except popup menus), just so that you see something after building
   * the project. Delete any components that you don't want shown initially.
   */
  window_gestion_troupeau_mb = create_window_gestion_troupeau_mb ();
  gtk_widget_show (window_gestion_troupeau_mb);
  GtkWidget* p1=lookup_widget(window_gestion_troupeau_mb,"treeview_1_mb");
  AfficherAnimal(p1,"troupeau.txt");
  GtkWidget* p2=lookup_widget(window_gestion_troupeau_mb,"treeview_2_mb");
  AfficherRechercheAnimal(p2,"troupeau.txt");
  GtkWidget* p3=lookup_widget(window_gestion_troupeau_mb,"label_nombre_veau_output_mb");
  GtkWidget* p4=lookup_widget(window_gestion_troupeau_mb,"label_nombre_brebis_output_mb");
  nbVeaux = nombre_veaux();
  snprintf(nombreVeaux, 30, "%d", nbVeaux);
  gtk_label_set_text(p3,nombreVeaux);
  nbBrebis = nombre_brebis();
  snprintf(nombreBrebis, 30, "%d", nbBrebis);
  gtk_label_set_text(p4,nombreBrebis);
  gtk_main ();
  return 0;
}

