/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <gtk/gtk.h>
#include<stdio.h>
#include<stdlib.h>
#include<string.h>
#include "interface.h"
#include "support.h"
#include"tree.h"
#include"troupeau.h"

int
main (int argc, char *argv[])
{
  GtkWidget *window_gestion_troupeau_mb,*window_mb;
  char nombreBrebis[30];
  char nombreVeaux[30];
  int nbBrebis,nbVeaux;

#ifdef ENABLE_NLS
  bindtextdomain (GETTEXT_PACKAGE, PACKAGE_LOCALE_DIR);
  bind_textdomain_codeset (GETTEXT_PACKAGE, "UTF-8");
  textdomain (GETTEXT_PACKAGE);
#endif

  gtk_set_locale ();
  gtk_init (&argc, &argv);

  add_pixmap_directory (PACKAGE_DATA_DIR "/" PACKAGE "/pixmaps");

  /*
   * The following code was added by Glade to create one of each component
   * (except popup menus), just so that you see something after building
   * the project. Delete any components that you don't want shown initially.
   */
  window_mb=create_window_mb();
  gtk_widget_show (window_mb);
  g_signal_connect(G_OBJECT(window_mb),
        "destroy", gtk_main_quit, NULL);
  gtk_main ();
  return 0;
}

