/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_windowSmartFarm (void);
GtkWidget* create_windowInscriValid__e (void);
GtkWidget* create_windowModifValid__e (void);
GtkWidget* create_windowSuppValid__e (void);
