/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_CalendarMain (void)
{
  GtkWidget *CalendarMain;
  GtkWidget *fixed4;
  GtkWidget *fixed23;
  GtkWidget *WelcomeText;
  GtkWidget *WelcomeText2;
  GtkWidget *GoToCheckCalendar;
  GtkWidget *GoToAddNewPlant;
  GtkWidget *ExitButton1;
  GtkWidget *image6;

  CalendarMain = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (CalendarMain), _("CalendarMain"));

  fixed4 = gtk_fixed_new ();
  gtk_widget_show (fixed4);
  gtk_container_add (GTK_CONTAINER (CalendarMain), fixed4);

  fixed23 = gtk_fixed_new ();
  gtk_widget_show (fixed23);
  gtk_fixed_put (GTK_FIXED (fixed4), fixed23, 688, 256);
  gtk_widget_set_size_request (fixed23, 50, 50);

  WelcomeText = gtk_label_new (_("Bienvenu \303\240 la gestion du calendrier !"));
  gtk_widget_show (WelcomeText);
  gtk_fixed_put (GTK_FIXED (fixed4), WelcomeText, 200, 24);
  gtk_widget_set_size_request (WelcomeText, 392, 72);

  WelcomeText2 = gtk_label_new (_("Vous voulez ..."));
  gtk_widget_show (WelcomeText2);
  gtk_fixed_put (GTK_FIXED (fixed4), WelcomeText2, 296, 88);
  gtk_widget_set_size_request (WelcomeText2, 192, 56);

  GoToCheckCalendar = gtk_button_new_with_mnemonic (_("V\303\251rifier le calendrier de plantations"));
  gtk_widget_show (GoToCheckCalendar);
  gtk_fixed_put (GTK_FIXED (fixed4), GoToCheckCalendar, 168, 176);
  gtk_widget_set_size_request (GoToCheckCalendar, 456, 72);

  GoToAddNewPlant = gtk_button_new_with_mnemonic (_("Ajouter une nouvelle plantation"));
  gtk_widget_show (GoToAddNewPlant);
  gtk_fixed_put (GTK_FIXED (fixed4), GoToAddNewPlant, 168, 288);
  gtk_widget_set_size_request (GoToAddNewPlant, 456, 72);

  ExitButton1 = gtk_button_new ();
  gtk_widget_show (ExitButton1);
  gtk_fixed_put (GTK_FIXED (fixed4), ExitButton1, 696, 24);
  gtk_widget_set_size_request (ExitButton1, 50, 56);

  image6 = gtk_image_new_from_stock ("gtk-stop", GTK_ICON_SIZE_DND);
  gtk_widget_show (image6);
  gtk_container_add (GTK_CONTAINER (ExitButton1), image6);

  g_signal_connect ((gpointer) GoToCheckCalendar, "clicked",
                    G_CALLBACK (on_GoToCheckCalendar_clicked),
                    NULL);
  g_signal_connect ((gpointer) GoToAddNewPlant, "clicked",
                    G_CALLBACK (on_GoToAddNewPlant_clicked),
                    NULL);
  g_signal_connect ((gpointer) ExitButton1, "clicked",
                    G_CALLBACK (on_ExitButton1_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (CalendarMain, CalendarMain, "CalendarMain");
  GLADE_HOOKUP_OBJECT (CalendarMain, fixed4, "fixed4");
  GLADE_HOOKUP_OBJECT (CalendarMain, fixed23, "fixed23");
  GLADE_HOOKUP_OBJECT (CalendarMain, WelcomeText, "WelcomeText");
  GLADE_HOOKUP_OBJECT (CalendarMain, WelcomeText2, "WelcomeText2");
  GLADE_HOOKUP_OBJECT (CalendarMain, GoToCheckCalendar, "GoToCheckCalendar");
  GLADE_HOOKUP_OBJECT (CalendarMain, GoToAddNewPlant, "GoToAddNewPlant");
  GLADE_HOOKUP_OBJECT (CalendarMain, ExitButton1, "ExitButton1");
  GLADE_HOOKUP_OBJECT (CalendarMain, image6, "image6");

  return CalendarMain;
}

GtkWidget*
create_CheckCalendar (void)
{
  GtkWidget *CheckCalendar;
  GtkWidget *fixed6;
  GtkWidget *ExitButton2;
  GtkWidget *image8;
  GtkWidget *PlantationPlan;
  GtkWidget *fixed10;
  GtkWidget *treeviewSpring;
  GtkWidget *ButtonEditSP;
  GtkWidget *alignment3;
  GtkWidget *hbox3;
  GtkWidget *image14;
  GtkWidget *label9;
  GtkWidget *ButtonDeleteSP;
  GtkWidget *alignment7;
  GtkWidget *hbox7;
  GtkWidget *image18;
  GtkWidget *label13;
  GtkWidget *LabelSpEditF;
  GtkWidget *LabelSpDelF;
  GtkWidget *LabelSpDelS;
  GtkWidget *SpringPlantListLabel;
  GtkWidget *fixed11;
  GtkWidget *treeviewSummer;
  GtkWidget *ButtonEditSU;
  GtkWidget *alignment4;
  GtkWidget *hbox4;
  GtkWidget *image15;
  GtkWidget *label10;
  GtkWidget *ButtonDeleteSU;
  GtkWidget *alignment8;
  GtkWidget *hbox8;
  GtkWidget *image19;
  GtkWidget *label14;
  GtkWidget *LabelSmEditF;
  GtkWidget *LabelSmDelF;
  GtkWidget *LabelSmDelS;
  GtkWidget *SummerPlantListLabel;
  GtkWidget *fixed12;
  GtkWidget *treeviewAutumn;
  GtkWidget *ButtonEditAU;
  GtkWidget *alignment5;
  GtkWidget *hbox5;
  GtkWidget *image16;
  GtkWidget *label11;
  GtkWidget *ButtonDeleteAU;
  GtkWidget *alignment9;
  GtkWidget *hbox9;
  GtkWidget *image20;
  GtkWidget *label15;
  GtkWidget *LabelAuEditF;
  GtkWidget *LabelAuDelF;
  GtkWidget *LabelAuDelS;
  GtkWidget *AutumnPlantListLabel;
  GtkWidget *fixed13;
  GtkWidget *treeviewWinter;
  GtkWidget *ButtonEditWI;
  GtkWidget *alignment6;
  GtkWidget *hbox6;
  GtkWidget *image17;
  GtkWidget *label12;
  GtkWidget *ButtonDeleteWI;
  GtkWidget *alignment10;
  GtkWidget *hbox10;
  GtkWidget *image21;
  GtkWidget *label16;
  GtkWidget *LabelWEditF;
  GtkWidget *LabelWDelF;
  GtkWidget *LabelWDelS;
  GtkWidget *WinterPlantListLabel;
  GtkWidget *CheckCalendarLabel;

  CheckCalendar = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (CheckCalendar), _("CheckCalendar"));

  fixed6 = gtk_fixed_new ();
  gtk_widget_show (fixed6);
  gtk_container_add (GTK_CONTAINER (CheckCalendar), fixed6);

  ExitButton2 = gtk_button_new ();
  gtk_widget_show (ExitButton2);
  gtk_fixed_put (GTK_FIXED (fixed6), ExitButton2, 848, 24);
  gtk_widget_set_size_request (ExitButton2, 48, 45);

  image8 = gtk_image_new_from_stock ("gtk-stop", GTK_ICON_SIZE_DND);
  gtk_widget_show (image8);
  gtk_container_add (GTK_CONTAINER (ExitButton2), image8);

  PlantationPlan = gtk_notebook_new ();
  gtk_widget_show (PlantationPlan);
  gtk_fixed_put (GTK_FIXED (fixed6), PlantationPlan, 96, 112);
  gtk_widget_set_size_request (PlantationPlan, 776, 560);

  fixed10 = gtk_fixed_new ();
  gtk_widget_show (fixed10);
  gtk_container_add (GTK_CONTAINER (PlantationPlan), fixed10);

  treeviewSpring = gtk_tree_view_new ();
  gtk_widget_show (treeviewSpring);
  gtk_fixed_put (GTK_FIXED (fixed10), treeviewSpring, 16, 48);
  gtk_widget_set_size_request (treeviewSpring, 416, 360);

  ButtonEditSP = gtk_button_new ();
  gtk_widget_show (ButtonEditSP);
  gtk_fixed_put (GTK_FIXED (fixed10), ButtonEditSP, 576, 64);
  gtk_widget_set_size_request (ButtonEditSP, 162, 56);

  alignment3 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment3);
  gtk_container_add (GTK_CONTAINER (ButtonEditSP), alignment3);

  hbox3 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox3);
  gtk_container_add (GTK_CONTAINER (alignment3), hbox3);

  image14 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_LARGE_TOOLBAR);
  gtk_widget_show (image14);
  gtk_box_pack_start (GTK_BOX (hbox3), image14, FALSE, FALSE, 0);

  label9 = gtk_label_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (label9);
  gtk_box_pack_start (GTK_BOX (hbox3), label9, FALSE, FALSE, 0);

  ButtonDeleteSP = gtk_button_new ();
  gtk_widget_show (ButtonDeleteSP);
  gtk_fixed_put (GTK_FIXED (fixed10), ButtonDeleteSP, 576, 232);
  gtk_widget_set_size_request (ButtonDeleteSP, 160, 56);

  alignment7 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment7);
  gtk_container_add (GTK_CONTAINER (ButtonDeleteSP), alignment7);

  hbox7 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox7);
  gtk_container_add (GTK_CONTAINER (alignment7), hbox7);

  image18 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_LARGE_TOOLBAR);
  gtk_widget_show (image18);
  gtk_box_pack_start (GTK_BOX (hbox7), image18, FALSE, FALSE, 0);

  label13 = gtk_label_new_with_mnemonic (_("Supprimer"));
  gtk_widget_show (label13);
  gtk_box_pack_start (GTK_BOX (hbox7), label13, FALSE, FALSE, 0);

  LabelSpEditF = gtk_label_new_with_mnemonic (_("<span foreground=\"red\"><b>Veuillez s\303\251lectionnner \nun \303\251l\303\251ment du tableau !</b></span>"));
  gtk_fixed_put (GTK_FIXED (fixed10), LabelSpEditF, 472, 136);
  gtk_widget_set_size_request (LabelSpEditF, 288, 72);
  gtk_label_set_use_markup (GTK_LABEL (LabelSpEditF), TRUE);
  gtk_label_set_justify (GTK_LABEL (LabelSpEditF), GTK_JUSTIFY_CENTER);

  LabelSpDelF = gtk_label_new_with_mnemonic (_("<span foreground=\"red\"><b>Veuillez s\303\251lectionner\n un \303\251lement du tableau</b></span>"));
  gtk_fixed_put (GTK_FIXED (fixed10), LabelSpDelF, 496, 304);
  gtk_widget_set_size_request (LabelSpDelF, 256, 64);
  gtk_label_set_use_markup (GTK_LABEL (LabelSpDelF), TRUE);
  gtk_label_set_justify (GTK_LABEL (LabelSpDelF), GTK_JUSTIFY_CENTER);

  LabelSpDelS = gtk_label_new_with_mnemonic (_("<span foreground=\"green\"><b>\303\251l\303\251ment supprim\303\251 avec succ\303\250s</b></span>"));
  gtk_fixed_put (GTK_FIXED (fixed10), LabelSpDelS, 488, 376);
  gtk_widget_set_size_request (LabelSpDelS, 272, 64);
  gtk_label_set_use_markup (GTK_LABEL (LabelSpDelS), TRUE);
  gtk_label_set_justify (GTK_LABEL (LabelSpDelS), GTK_JUSTIFY_CENTER);

  SpringPlantListLabel = gtk_label_new (_("printemps"));
  gtk_widget_show (SpringPlantListLabel);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (PlantationPlan), gtk_notebook_get_nth_page (GTK_NOTEBOOK (PlantationPlan), 0), SpringPlantListLabel);

  fixed11 = gtk_fixed_new ();
  gtk_widget_show (fixed11);
  gtk_container_add (GTK_CONTAINER (PlantationPlan), fixed11);

  treeviewSummer = gtk_tree_view_new ();
  gtk_widget_show (treeviewSummer);
  gtk_fixed_put (GTK_FIXED (fixed11), treeviewSummer, 16, 48);
  gtk_widget_set_size_request (treeviewSummer, 416, 376);

  ButtonEditSU = gtk_button_new ();
  gtk_widget_show (ButtonEditSU);
  gtk_fixed_put (GTK_FIXED (fixed11), ButtonEditSU, 584, 56);
  gtk_widget_set_size_request (ButtonEditSU, 154, 53);

  alignment4 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment4);
  gtk_container_add (GTK_CONTAINER (ButtonEditSU), alignment4);

  hbox4 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox4);
  gtk_container_add (GTK_CONTAINER (alignment4), hbox4);

  image15 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_LARGE_TOOLBAR);
  gtk_widget_show (image15);
  gtk_box_pack_start (GTK_BOX (hbox4), image15, FALSE, FALSE, 0);

  label10 = gtk_label_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (label10);
  gtk_box_pack_start (GTK_BOX (hbox4), label10, FALSE, FALSE, 0);

  ButtonDeleteSU = gtk_button_new ();
  gtk_widget_show (ButtonDeleteSU);
  gtk_fixed_put (GTK_FIXED (fixed11), ButtonDeleteSU, 584, 240);
  gtk_widget_set_size_request (ButtonDeleteSU, 152, 56);

  alignment8 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment8);
  gtk_container_add (GTK_CONTAINER (ButtonDeleteSU), alignment8);

  hbox8 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox8);
  gtk_container_add (GTK_CONTAINER (alignment8), hbox8);

  image19 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_LARGE_TOOLBAR);
  gtk_widget_show (image19);
  gtk_box_pack_start (GTK_BOX (hbox8), image19, FALSE, FALSE, 0);

  label14 = gtk_label_new_with_mnemonic (_("Supprimer"));
  gtk_widget_show (label14);
  gtk_box_pack_start (GTK_BOX (hbox8), label14, FALSE, FALSE, 0);

  LabelSmEditF = gtk_label_new_with_mnemonic (_("<span foreground=\"red\"><b>Veuillez s\303\251lectionnner \nun \303\251l\303\251ment du tableau !</b></span>"));
  gtk_fixed_put (GTK_FIXED (fixed11), LabelSmEditF, 512, 136);
  gtk_widget_set_size_request (LabelSmEditF, 248, 64);
  gtk_label_set_use_markup (GTK_LABEL (LabelSmEditF), TRUE);
  gtk_label_set_justify (GTK_LABEL (LabelSmEditF), GTK_JUSTIFY_CENTER);

  LabelSmDelF = gtk_label_new_with_mnemonic (_("<span foreground=\"red\"><b>Veuillez s\303\251lectionner\n un \303\251lement du tableau</b></span>"));
  gtk_fixed_put (GTK_FIXED (fixed11), LabelSmDelF, 496, 320);
  gtk_widget_set_size_request (LabelSmDelF, 256, 64);
  gtk_label_set_use_markup (GTK_LABEL (LabelSmDelF), TRUE);
  gtk_label_set_justify (GTK_LABEL (LabelSmDelF), GTK_JUSTIFY_CENTER);

  LabelSmDelS = gtk_label_new_with_mnemonic (_("<span foreground=\"green\"><b>\303\251l\303\251ment supprim\303\251 avec succ\303\250s</b></span>"));
  gtk_fixed_put (GTK_FIXED (fixed11), LabelSmDelS, 496, 392);
  gtk_widget_set_size_request (LabelSmDelS, 264, 72);
  gtk_label_set_use_markup (GTK_LABEL (LabelSmDelS), TRUE);
  gtk_label_set_justify (GTK_LABEL (LabelSmDelS), GTK_JUSTIFY_CENTER);

  SummerPlantListLabel = gtk_label_new (_("\303\251t\303\251"));
  gtk_widget_show (SummerPlantListLabel);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (PlantationPlan), gtk_notebook_get_nth_page (GTK_NOTEBOOK (PlantationPlan), 1), SummerPlantListLabel);

  fixed12 = gtk_fixed_new ();
  gtk_widget_show (fixed12);
  gtk_container_add (GTK_CONTAINER (PlantationPlan), fixed12);

  treeviewAutumn = gtk_tree_view_new ();
  gtk_widget_show (treeviewAutumn);
  gtk_fixed_put (GTK_FIXED (fixed12), treeviewAutumn, 16, 40);
  gtk_widget_set_size_request (treeviewAutumn, 424, 392);

  ButtonEditAU = gtk_button_new ();
  gtk_widget_show (ButtonEditAU);
  gtk_fixed_put (GTK_FIXED (fixed12), ButtonEditAU, 576, 56);
  gtk_widget_set_size_request (ButtonEditAU, 160, 56);

  alignment5 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment5);
  gtk_container_add (GTK_CONTAINER (ButtonEditAU), alignment5);

  hbox5 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox5);
  gtk_container_add (GTK_CONTAINER (alignment5), hbox5);

  image16 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_LARGE_TOOLBAR);
  gtk_widget_show (image16);
  gtk_box_pack_start (GTK_BOX (hbox5), image16, FALSE, FALSE, 0);

  label11 = gtk_label_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (label11);
  gtk_box_pack_start (GTK_BOX (hbox5), label11, FALSE, FALSE, 0);

  ButtonDeleteAU = gtk_button_new ();
  gtk_widget_show (ButtonDeleteAU);
  gtk_fixed_put (GTK_FIXED (fixed12), ButtonDeleteAU, 576, 256);
  gtk_widget_set_size_request (ButtonDeleteAU, 160, 56);

  alignment9 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment9);
  gtk_container_add (GTK_CONTAINER (ButtonDeleteAU), alignment9);

  hbox9 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox9);
  gtk_container_add (GTK_CONTAINER (alignment9), hbox9);

  image20 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_LARGE_TOOLBAR);
  gtk_widget_show (image20);
  gtk_box_pack_start (GTK_BOX (hbox9), image20, FALSE, FALSE, 0);

  label15 = gtk_label_new_with_mnemonic (_("Supprimer"));
  gtk_widget_show (label15);
  gtk_box_pack_start (GTK_BOX (hbox9), label15, FALSE, FALSE, 0);

  LabelAuEditF = gtk_label_new_with_mnemonic (_("<span foreground=\"red\"><b>Veuillez s\303\251lectionnner \nun \303\251l\303\251ment du tableau !</b></span>"));
  gtk_fixed_put (GTK_FIXED (fixed12), LabelAuEditF, 488, 144);
  gtk_widget_set_size_request (LabelAuEditF, 264, 64);
  gtk_label_set_use_markup (GTK_LABEL (LabelAuEditF), TRUE);
  gtk_label_set_justify (GTK_LABEL (LabelAuEditF), GTK_JUSTIFY_CENTER);

  LabelAuDelF = gtk_label_new_with_mnemonic (_("<span foreground=\"red\"><b>Veuillez s\303\251lectionner\n un \303\251lement du tableau</b></span>"));
  gtk_fixed_put (GTK_FIXED (fixed12), LabelAuDelF, 480, 336);
  gtk_widget_set_size_request (LabelAuDelF, 272, 64);
  gtk_label_set_use_markup (GTK_LABEL (LabelAuDelF), TRUE);
  gtk_label_set_justify (GTK_LABEL (LabelAuDelF), GTK_JUSTIFY_CENTER);

  LabelAuDelS = gtk_label_new_with_mnemonic (_("<span foreground=\"green\"><b>\303\251l\303\251ment supprim\303\251 avec succ\303\250s</b></span>"));
  gtk_fixed_put (GTK_FIXED (fixed12), LabelAuDelS, 488, 424);
  gtk_widget_set_size_request (LabelAuDelS, 272, 72);
  gtk_label_set_use_markup (GTK_LABEL (LabelAuDelS), TRUE);
  gtk_label_set_justify (GTK_LABEL (LabelAuDelS), GTK_JUSTIFY_CENTER);

  AutumnPlantListLabel = gtk_label_new (_("automne"));
  gtk_widget_show (AutumnPlantListLabel);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (PlantationPlan), gtk_notebook_get_nth_page (GTK_NOTEBOOK (PlantationPlan), 2), AutumnPlantListLabel);

  fixed13 = gtk_fixed_new ();
  gtk_widget_show (fixed13);
  gtk_container_add (GTK_CONTAINER (PlantationPlan), fixed13);

  treeviewWinter = gtk_tree_view_new ();
  gtk_widget_show (treeviewWinter);
  gtk_fixed_put (GTK_FIXED (fixed13), treeviewWinter, 16, 24);
  gtk_widget_set_size_request (treeviewWinter, 408, 416);

  ButtonEditWI = gtk_button_new ();
  gtk_widget_show (ButtonEditWI);
  gtk_fixed_put (GTK_FIXED (fixed13), ButtonEditWI, 584, 72);
  gtk_widget_set_size_request (ButtonEditWI, 160, 56);

  alignment6 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment6);
  gtk_container_add (GTK_CONTAINER (ButtonEditWI), alignment6);

  hbox6 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox6);
  gtk_container_add (GTK_CONTAINER (alignment6), hbox6);

  image17 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_LARGE_TOOLBAR);
  gtk_widget_show (image17);
  gtk_box_pack_start (GTK_BOX (hbox6), image17, FALSE, FALSE, 0);

  label12 = gtk_label_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (label12);
  gtk_box_pack_start (GTK_BOX (hbox6), label12, FALSE, FALSE, 0);

  ButtonDeleteWI = gtk_button_new ();
  gtk_widget_show (ButtonDeleteWI);
  gtk_fixed_put (GTK_FIXED (fixed13), ButtonDeleteWI, 584, 272);
  gtk_widget_set_size_request (ButtonDeleteWI, 152, 56);

  alignment10 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment10);
  gtk_container_add (GTK_CONTAINER (ButtonDeleteWI), alignment10);

  hbox10 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox10);
  gtk_container_add (GTK_CONTAINER (alignment10), hbox10);

  image21 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_LARGE_TOOLBAR);
  gtk_widget_show (image21);
  gtk_box_pack_start (GTK_BOX (hbox10), image21, FALSE, FALSE, 0);

  label16 = gtk_label_new_with_mnemonic (_("Supprimer"));
  gtk_widget_show (label16);
  gtk_box_pack_start (GTK_BOX (hbox10), label16, FALSE, FALSE, 0);

  LabelWEditF = gtk_label_new_with_mnemonic (_("<span foreground=\"red\"><b>Veuillez s\303\251lectionnner \nun \303\251l\303\251ment du tableau !</b></span>"));
  gtk_fixed_put (GTK_FIXED (fixed13), LabelWEditF, 504, 152);
  gtk_widget_set_size_request (LabelWEditF, 256, 64);
  gtk_label_set_use_markup (GTK_LABEL (LabelWEditF), TRUE);
  gtk_label_set_justify (GTK_LABEL (LabelWEditF), GTK_JUSTIFY_CENTER);

  LabelWDelF = gtk_label_new_with_mnemonic (_("<span foreground=\"red\"><b>Veuillez s\303\251lectionner\n un \303\251lement du tableau</b></span>"));
  gtk_fixed_put (GTK_FIXED (fixed13), LabelWDelF, 480, 352);
  gtk_widget_set_size_request (LabelWDelF, 272, 64);
  gtk_label_set_use_markup (GTK_LABEL (LabelWDelF), TRUE);
  gtk_label_set_justify (GTK_LABEL (LabelWDelF), GTK_JUSTIFY_CENTER);

  LabelWDelS = gtk_label_new_with_mnemonic (_("<span foreground=\"green\"><b>\303\251l\303\251ment supprim\303\251 avec succ\303\250s</b></span>"));
  gtk_fixed_put (GTK_FIXED (fixed13), LabelWDelS, 496, 416);
  gtk_widget_set_size_request (LabelWDelS, 264, 72);
  gtk_label_set_use_markup (GTK_LABEL (LabelWDelS), TRUE);
  gtk_label_set_justify (GTK_LABEL (LabelWDelS), GTK_JUSTIFY_CENTER);

  WinterPlantListLabel = gtk_label_new (_("hiver"));
  gtk_widget_show (WinterPlantListLabel);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (PlantationPlan), gtk_notebook_get_nth_page (GTK_NOTEBOOK (PlantationPlan), 3), WinterPlantListLabel);

  CheckCalendarLabel = gtk_label_new (_("Les plantations plannifi\303\251 pour cette ann\303\251e :"));
  gtk_widget_show (CheckCalendarLabel);
  gtk_fixed_put (GTK_FIXED (fixed6), CheckCalendarLabel, 256, 24);
  gtk_widget_set_size_request (CheckCalendarLabel, 448, 72);

  g_signal_connect ((gpointer) ExitButton2, "clicked",
                    G_CALLBACK (on_ExitButton2_clicked),
                    NULL);
  g_signal_connect ((gpointer) treeviewSpring, "row_activated",
                    G_CALLBACK (on_treeviewSpring_row_activated),
                    NULL);
  g_signal_connect ((gpointer) ButtonEditSP, "clicked",
                    G_CALLBACK (on_ButtonEditSP_clicked),
                    NULL);
  g_signal_connect ((gpointer) ButtonDeleteSP, "clicked",
                    G_CALLBACK (on_ButtonDeleteSP_clicked),
                    NULL);
  g_signal_connect ((gpointer) treeviewSummer, "row_activated",
                    G_CALLBACK (on_treeviewSummer_row_activated),
                    NULL);
  g_signal_connect ((gpointer) ButtonEditSU, "clicked",
                    G_CALLBACK (on_ButtonEditSU_clicked),
                    NULL);
  g_signal_connect ((gpointer) ButtonDeleteSU, "clicked",
                    G_CALLBACK (on_ButtonDeleteSU_clicked),
                    NULL);
  g_signal_connect ((gpointer) treeviewAutumn, "row_activated",
                    G_CALLBACK (on_treeviewAutumn_row_activated),
                    NULL);
  g_signal_connect ((gpointer) ButtonEditAU, "clicked",
                    G_CALLBACK (on_ButtonEditAU_clicked),
                    NULL);
  g_signal_connect ((gpointer) ButtonDeleteAU, "clicked",
                    G_CALLBACK (on_ButtonDeleteAU_clicked),
                    NULL);
  g_signal_connect ((gpointer) treeviewWinter, "row_activated",
                    G_CALLBACK (on_treeviewWinter_row_activated),
                    NULL);
  g_signal_connect ((gpointer) ButtonEditWI, "clicked",
                    G_CALLBACK (on_ButtonEditWI_clicked),
                    NULL);
  g_signal_connect ((gpointer) ButtonDeleteWI, "clicked",
                    G_CALLBACK (on_ButtonDeleteWI_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (CheckCalendar, CheckCalendar, "CheckCalendar");
  GLADE_HOOKUP_OBJECT (CheckCalendar, fixed6, "fixed6");
  GLADE_HOOKUP_OBJECT (CheckCalendar, ExitButton2, "ExitButton2");
  GLADE_HOOKUP_OBJECT (CheckCalendar, image8, "image8");
  GLADE_HOOKUP_OBJECT (CheckCalendar, PlantationPlan, "PlantationPlan");
  GLADE_HOOKUP_OBJECT (CheckCalendar, fixed10, "fixed10");
  GLADE_HOOKUP_OBJECT (CheckCalendar, treeviewSpring, "treeviewSpring");
  GLADE_HOOKUP_OBJECT (CheckCalendar, ButtonEditSP, "ButtonEditSP");
  GLADE_HOOKUP_OBJECT (CheckCalendar, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (CheckCalendar, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (CheckCalendar, image14, "image14");
  GLADE_HOOKUP_OBJECT (CheckCalendar, label9, "label9");
  GLADE_HOOKUP_OBJECT (CheckCalendar, ButtonDeleteSP, "ButtonDeleteSP");
  GLADE_HOOKUP_OBJECT (CheckCalendar, alignment7, "alignment7");
  GLADE_HOOKUP_OBJECT (CheckCalendar, hbox7, "hbox7");
  GLADE_HOOKUP_OBJECT (CheckCalendar, image18, "image18");
  GLADE_HOOKUP_OBJECT (CheckCalendar, label13, "label13");
  GLADE_HOOKUP_OBJECT (CheckCalendar, LabelSpEditF, "LabelSpEditF");
  GLADE_HOOKUP_OBJECT (CheckCalendar, LabelSpDelF, "LabelSpDelF");
  GLADE_HOOKUP_OBJECT (CheckCalendar, LabelSpDelS, "LabelSpDelS");
  GLADE_HOOKUP_OBJECT (CheckCalendar, SpringPlantListLabel, "SpringPlantListLabel");
  GLADE_HOOKUP_OBJECT (CheckCalendar, fixed11, "fixed11");
  GLADE_HOOKUP_OBJECT (CheckCalendar, treeviewSummer, "treeviewSummer");
  GLADE_HOOKUP_OBJECT (CheckCalendar, ButtonEditSU, "ButtonEditSU");
  GLADE_HOOKUP_OBJECT (CheckCalendar, alignment4, "alignment4");
  GLADE_HOOKUP_OBJECT (CheckCalendar, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (CheckCalendar, image15, "image15");
  GLADE_HOOKUP_OBJECT (CheckCalendar, label10, "label10");
  GLADE_HOOKUP_OBJECT (CheckCalendar, ButtonDeleteSU, "ButtonDeleteSU");
  GLADE_HOOKUP_OBJECT (CheckCalendar, alignment8, "alignment8");
  GLADE_HOOKUP_OBJECT (CheckCalendar, hbox8, "hbox8");
  GLADE_HOOKUP_OBJECT (CheckCalendar, image19, "image19");
  GLADE_HOOKUP_OBJECT (CheckCalendar, label14, "label14");
  GLADE_HOOKUP_OBJECT (CheckCalendar, LabelSmEditF, "LabelSmEditF");
  GLADE_HOOKUP_OBJECT (CheckCalendar, LabelSmDelF, "LabelSmDelF");
  GLADE_HOOKUP_OBJECT (CheckCalendar, LabelSmDelS, "LabelSmDelS");
  GLADE_HOOKUP_OBJECT (CheckCalendar, SummerPlantListLabel, "SummerPlantListLabel");
  GLADE_HOOKUP_OBJECT (CheckCalendar, fixed12, "fixed12");
  GLADE_HOOKUP_OBJECT (CheckCalendar, treeviewAutumn, "treeviewAutumn");
  GLADE_HOOKUP_OBJECT (CheckCalendar, ButtonEditAU, "ButtonEditAU");
  GLADE_HOOKUP_OBJECT (CheckCalendar, alignment5, "alignment5");
  GLADE_HOOKUP_OBJECT (CheckCalendar, hbox5, "hbox5");
  GLADE_HOOKUP_OBJECT (CheckCalendar, image16, "image16");
  GLADE_HOOKUP_OBJECT (CheckCalendar, label11, "label11");
  GLADE_HOOKUP_OBJECT (CheckCalendar, ButtonDeleteAU, "ButtonDeleteAU");
  GLADE_HOOKUP_OBJECT (CheckCalendar, alignment9, "alignment9");
  GLADE_HOOKUP_OBJECT (CheckCalendar, hbox9, "hbox9");
  GLADE_HOOKUP_OBJECT (CheckCalendar, image20, "image20");
  GLADE_HOOKUP_OBJECT (CheckCalendar, label15, "label15");
  GLADE_HOOKUP_OBJECT (CheckCalendar, LabelAuEditF, "LabelAuEditF");
  GLADE_HOOKUP_OBJECT (CheckCalendar, LabelAuDelF, "LabelAuDelF");
  GLADE_HOOKUP_OBJECT (CheckCalendar, LabelAuDelS, "LabelAuDelS");
  GLADE_HOOKUP_OBJECT (CheckCalendar, AutumnPlantListLabel, "AutumnPlantListLabel");
  GLADE_HOOKUP_OBJECT (CheckCalendar, fixed13, "fixed13");
  GLADE_HOOKUP_OBJECT (CheckCalendar, treeviewWinter, "treeviewWinter");
  GLADE_HOOKUP_OBJECT (CheckCalendar, ButtonEditWI, "ButtonEditWI");
  GLADE_HOOKUP_OBJECT (CheckCalendar, alignment6, "alignment6");
  GLADE_HOOKUP_OBJECT (CheckCalendar, hbox6, "hbox6");
  GLADE_HOOKUP_OBJECT (CheckCalendar, image17, "image17");
  GLADE_HOOKUP_OBJECT (CheckCalendar, label12, "label12");
  GLADE_HOOKUP_OBJECT (CheckCalendar, ButtonDeleteWI, "ButtonDeleteWI");
  GLADE_HOOKUP_OBJECT (CheckCalendar, alignment10, "alignment10");
  GLADE_HOOKUP_OBJECT (CheckCalendar, hbox10, "hbox10");
  GLADE_HOOKUP_OBJECT (CheckCalendar, image21, "image21");
  GLADE_HOOKUP_OBJECT (CheckCalendar, label16, "label16");
  GLADE_HOOKUP_OBJECT (CheckCalendar, LabelWEditF, "LabelWEditF");
  GLADE_HOOKUP_OBJECT (CheckCalendar, LabelWDelF, "LabelWDelF");
  GLADE_HOOKUP_OBJECT (CheckCalendar, LabelWDelS, "LabelWDelS");
  GLADE_HOOKUP_OBJECT (CheckCalendar, WinterPlantListLabel, "WinterPlantListLabel");
  GLADE_HOOKUP_OBJECT (CheckCalendar, CheckCalendarLabel, "CheckCalendarLabel");

  return CheckCalendar;
}

GtkWidget*
create_ChoosePlant (void)
{
  GtkWidget *ChoosePlant;
  GtkWidget *fixed15;
  GtkWidget *calendarPlanting;
  GtkWidget *calendarHarvesting;
  GtkWidget *ExitButton3;
  GtkWidget *image10;
  GtkWidget *labelRadioboxSeason;
  GtkWidget *RadioAutumn;
  GSList *RadioAutumn_group = NULL;
  GtkWidget *RadioSummer;
  GtkWidget *RadioSpring;
  GtkWidget *RadioWinter;
  GtkWidget *ChoosePlantLabel;
  GtkWidget *comboboxentry1;
  GtkWidget *labelCalendar2;
  GtkWidget *labelCalendar1;
  GtkWidget *ConfirmPlantButton;
  GtkWidget *LabelErrorRadio;
  GtkWidget *LabelErrorCheckbox;
  GtkWidget *LabelSuccessAdd;
  GtkWidget *ReturnToCalendar;

  ChoosePlant = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (ChoosePlant), _("ChoosePlant"));

  fixed15 = gtk_fixed_new ();
  gtk_widget_show (fixed15);
  gtk_container_add (GTK_CONTAINER (ChoosePlant), fixed15);

  calendarPlanting = gtk_calendar_new ();
  gtk_widget_show (calendarPlanting);
  gtk_fixed_put (GTK_FIXED (fixed15), calendarPlanting, 32, 424);
  gtk_widget_set_size_request (calendarPlanting, 312, 240);
  gtk_calendar_display_options (GTK_CALENDAR (calendarPlanting),
                                GTK_CALENDAR_SHOW_HEADING
                                | GTK_CALENDAR_SHOW_DAY_NAMES);

  calendarHarvesting = gtk_calendar_new ();
  gtk_widget_show (calendarHarvesting);
  gtk_fixed_put (GTK_FIXED (fixed15), calendarHarvesting, 688, 424);
  gtk_widget_set_size_request (calendarHarvesting, 304, 240);
  gtk_calendar_display_options (GTK_CALENDAR (calendarHarvesting),
                                GTK_CALENDAR_SHOW_HEADING
                                | GTK_CALENDAR_SHOW_DAY_NAMES);

  ExitButton3 = gtk_button_new ();
  gtk_widget_show (ExitButton3);
  gtk_fixed_put (GTK_FIXED (fixed15), ExitButton3, 968, 24);
  gtk_widget_set_size_request (ExitButton3, 48, 48);

  image10 = gtk_image_new_from_stock ("gtk-stop", GTK_ICON_SIZE_DND);
  gtk_widget_show (image10);
  gtk_container_add (GTK_CONTAINER (ExitButton3), image10);

  labelRadioboxSeason = gtk_label_new (_("Choisissez la saison"));
  gtk_widget_show (labelRadioboxSeason);
  gtk_fixed_put (GTK_FIXED (fixed15), labelRadioboxSeason, 360, 0);
  gtk_widget_set_size_request (labelRadioboxSeason, 249, 56);

  RadioAutumn = gtk_radio_button_new_with_mnemonic (NULL, _("Automne"));
  gtk_widget_show (RadioAutumn);
  gtk_fixed_put (GTK_FIXED (fixed15), RadioAutumn, 536, 64);
  gtk_widget_set_size_request (RadioAutumn, 152, 40);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (RadioAutumn), RadioAutumn_group);
  RadioAutumn_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (RadioAutumn));

  RadioSummer = gtk_radio_button_new_with_mnemonic (NULL, _("\303\211t\303\251"));
  gtk_widget_show (RadioSummer);
  gtk_fixed_put (GTK_FIXED (fixed15), RadioSummer, 288, 64);
  gtk_widget_set_size_request (RadioSummer, 152, 40);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (RadioSummer), RadioAutumn_group);
  RadioAutumn_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (RadioSummer));

  RadioSpring = gtk_radio_button_new_with_mnemonic (NULL, _("Printemps"));
  gtk_widget_show (RadioSpring);
  gtk_fixed_put (GTK_FIXED (fixed15), RadioSpring, 32, 56);
  gtk_widget_set_size_request (RadioSpring, 184, 48);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (RadioSpring), RadioAutumn_group);
  RadioAutumn_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (RadioSpring));

  RadioWinter = gtk_radio_button_new_with_mnemonic (NULL, _("Hiver"));
  gtk_widget_show (RadioWinter);
  gtk_fixed_put (GTK_FIXED (fixed15), RadioWinter, 784, 64);
  gtk_widget_set_size_request (RadioWinter, 152, 40);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (RadioWinter), RadioAutumn_group);
  RadioAutumn_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (RadioWinter));

  ChoosePlantLabel = gtk_label_new (_("Choisissez la plante :"));
  gtk_widget_show (ChoosePlantLabel);
  gtk_fixed_put (GTK_FIXED (fixed15), ChoosePlantLabel, 272, 152);
  gtk_widget_set_size_request (ChoosePlantLabel, 432, 64);

  comboboxentry1 = gtk_combo_box_entry_new_text ();
  gtk_widget_show (comboboxentry1);
  gtk_fixed_put (GTK_FIXED (fixed15), comboboxentry1, 168, 224);
  gtk_widget_set_size_request (comboboxentry1, 648, 64);
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry1), _("Aubergine"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry1), _("Avoine"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry1), _("Bl\303\251"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry1), _("Cor\303\250te_potag\303\250re"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry1), _("Chou_pomm\303\251"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry1), _("F\303\250ves"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry1), _("Laitue"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry1), _("Ma\303\257s"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry1), _("Melon"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry1), _("Orge"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry1), _("Oignon_blanc"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry1), _("Pomme_de_terre"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry1), _("Pois"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry1), _("Tomates"));

  labelCalendar2 = gtk_label_new (_("Date projet\303\251 de r\303\251colte"));
  gtk_widget_show (labelCalendar2);
  gtk_fixed_put (GTK_FIXED (fixed15), labelCalendar2, 712, 376);
  gtk_widget_set_size_request (labelCalendar2, 264, 40);

  labelCalendar1 = gtk_label_new (_("Date d'ensemencement"));
  gtk_widget_show (labelCalendar1);
  gtk_fixed_put (GTK_FIXED (fixed15), labelCalendar1, 48, 376);
  gtk_widget_set_size_request (labelCalendar1, 280, 40);

  ConfirmPlantButton = gtk_button_new_with_mnemonic (_("Confirmer la s\303\251lection"));
  gtk_widget_show (ConfirmPlantButton);
  gtk_fixed_put (GTK_FIXED (fixed15), ConfirmPlantButton, 248, 728);
  gtk_widget_set_size_request (ConfirmPlantButton, 218, 64);

  LabelErrorRadio = gtk_label_new_with_mnemonic (_("<span foreground=\"red\"><b>Veuillez choisir une saison ! </b></span>"));
  gtk_fixed_put (GTK_FIXED (fixed15), LabelErrorRadio, 280, 128);
  gtk_widget_set_size_request (LabelErrorRadio, 432, 32);
  gtk_label_set_use_markup (GTK_LABEL (LabelErrorRadio), TRUE);
  gtk_label_set_justify (GTK_LABEL (LabelErrorRadio), GTK_JUSTIFY_CENTER);

  LabelErrorCheckbox = gtk_label_new_with_mnemonic (_("<span foreground=\"red\"><b>Veuillez Choisir une plante !</b></span>"));
  gtk_fixed_put (GTK_FIXED (fixed15), LabelErrorCheckbox, 296, 320);
  gtk_widget_set_size_request (LabelErrorCheckbox, 392, 40);
  gtk_label_set_use_markup (GTK_LABEL (LabelErrorCheckbox), TRUE);
  gtk_label_set_justify (GTK_LABEL (LabelErrorCheckbox), GTK_JUSTIFY_CENTER);

  LabelSuccessAdd = gtk_label_new_with_mnemonic (_("<span foreground=\"green\"><b>Nouvelle plantation ajout\303\251 avec succ\303\250s! </b></span>"));
  gtk_fixed_put (GTK_FIXED (fixed15), LabelSuccessAdd, 320, 688);
  gtk_widget_set_size_request (LabelSuccessAdd, 408, 32);
  gtk_label_set_use_markup (GTK_LABEL (LabelSuccessAdd), TRUE);
  gtk_label_set_justify (GTK_LABEL (LabelSuccessAdd), GTK_JUSTIFY_CENTER);

  ReturnToCalendar = gtk_button_new_with_mnemonic (_("Retourner au calendrier"));
  gtk_widget_show (ReturnToCalendar);
  gtk_fixed_put (GTK_FIXED (fixed15), ReturnToCalendar, 552, 728);
  gtk_widget_set_size_request (ReturnToCalendar, 224, 64);

  g_signal_connect ((gpointer) ExitButton3, "clicked",
                    G_CALLBACK (on_ExitButton3_clicked),
                    NULL);
  g_signal_connect ((gpointer) RadioAutumn, "toggled",
                    G_CALLBACK (on_RadioAutumn_toggled),
                    NULL);
  g_signal_connect ((gpointer) RadioSummer, "toggled",
                    G_CALLBACK (on_RadioSummer_toggled),
                    NULL);
  g_signal_connect ((gpointer) RadioSpring, "toggled",
                    G_CALLBACK (on_RadioSpring_toggled),
                    NULL);
  g_signal_connect ((gpointer) RadioWinter, "toggled",
                    G_CALLBACK (on_RadioWinter_toggled),
                    NULL);
  g_signal_connect ((gpointer) ConfirmPlantButton, "clicked",
                    G_CALLBACK (on_ConfirmPlantButton_clicked),
                    NULL);
  g_signal_connect ((gpointer) ReturnToCalendar, "clicked",
                    G_CALLBACK (on_ReturnToCalendar_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (ChoosePlant, ChoosePlant, "ChoosePlant");
  GLADE_HOOKUP_OBJECT (ChoosePlant, fixed15, "fixed15");
  GLADE_HOOKUP_OBJECT (ChoosePlant, calendarPlanting, "calendarPlanting");
  GLADE_HOOKUP_OBJECT (ChoosePlant, calendarHarvesting, "calendarHarvesting");
  GLADE_HOOKUP_OBJECT (ChoosePlant, ExitButton3, "ExitButton3");
  GLADE_HOOKUP_OBJECT (ChoosePlant, image10, "image10");
  GLADE_HOOKUP_OBJECT (ChoosePlant, labelRadioboxSeason, "labelRadioboxSeason");
  GLADE_HOOKUP_OBJECT (ChoosePlant, RadioAutumn, "RadioAutumn");
  GLADE_HOOKUP_OBJECT (ChoosePlant, RadioSummer, "RadioSummer");
  GLADE_HOOKUP_OBJECT (ChoosePlant, RadioSpring, "RadioSpring");
  GLADE_HOOKUP_OBJECT (ChoosePlant, RadioWinter, "RadioWinter");
  GLADE_HOOKUP_OBJECT (ChoosePlant, ChoosePlantLabel, "ChoosePlantLabel");
  GLADE_HOOKUP_OBJECT (ChoosePlant, comboboxentry1, "comboboxentry1");
  GLADE_HOOKUP_OBJECT (ChoosePlant, labelCalendar2, "labelCalendar2");
  GLADE_HOOKUP_OBJECT (ChoosePlant, labelCalendar1, "labelCalendar1");
  GLADE_HOOKUP_OBJECT (ChoosePlant, ConfirmPlantButton, "ConfirmPlantButton");
  GLADE_HOOKUP_OBJECT (ChoosePlant, LabelErrorRadio, "LabelErrorRadio");
  GLADE_HOOKUP_OBJECT (ChoosePlant, LabelErrorCheckbox, "LabelErrorCheckbox");
  GLADE_HOOKUP_OBJECT (ChoosePlant, LabelSuccessAdd, "LabelSuccessAdd");
  GLADE_HOOKUP_OBJECT (ChoosePlant, ReturnToCalendar, "ReturnToCalendar");

  return ChoosePlant;
}

GtkWidget*
create_EditPlant (void)
{
  GtkWidget *EditPlant;
  GtkWidget *fixed24;
  GtkWidget *calendarEditPlanting;
  GtkWidget *calendarEditHarvesting;
  GtkWidget *labelEditCal4;
  GtkWidget *labelEditCal3;
  GtkWidget *ExitButton5;
  GtkWidget *image22;
  GtkWidget *labelEditDate;
  GtkWidget *ButtonConfirmEdit;
  GtkWidget *buttonReturnCal;
  GtkWidget *LabelSuccessEdit;

  EditPlant = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (EditPlant), _("EditPlant"));

  fixed24 = gtk_fixed_new ();
  gtk_widget_show (fixed24);
  gtk_container_add (GTK_CONTAINER (EditPlant), fixed24);

  calendarEditPlanting = gtk_calendar_new ();
  gtk_widget_show (calendarEditPlanting);
  gtk_fixed_put (GTK_FIXED (fixed24), calendarEditPlanting, 64, 256);
  gtk_widget_set_size_request (calendarEditPlanting, 352, 224);
  gtk_calendar_display_options (GTK_CALENDAR (calendarEditPlanting),
                                GTK_CALENDAR_SHOW_HEADING
                                | GTK_CALENDAR_SHOW_DAY_NAMES);

  calendarEditHarvesting = gtk_calendar_new ();
  gtk_widget_show (calendarEditHarvesting);
  gtk_fixed_put (GTK_FIXED (fixed24), calendarEditHarvesting, 520, 256);
  gtk_widget_set_size_request (calendarEditHarvesting, 357, 224);
  gtk_calendar_display_options (GTK_CALENDAR (calendarEditHarvesting),
                                GTK_CALENDAR_SHOW_HEADING
                                | GTK_CALENDAR_SHOW_DAY_NAMES);

  labelEditCal4 = gtk_label_new (_("Nouvelle date de r\303\251colte"));
  gtk_widget_show (labelEditCal4);
  gtk_fixed_put (GTK_FIXED (fixed24), labelEditCal4, 544, 200);
  gtk_widget_set_size_request (labelEditCal4, 312, 40);

  labelEditCal3 = gtk_label_new (_("Nouvelle date d'encemencement"));
  gtk_widget_show (labelEditCal3);
  gtk_fixed_put (GTK_FIXED (fixed24), labelEditCal3, 96, 200);
  gtk_widget_set_size_request (labelEditCal3, 280, 40);

  ExitButton5 = gtk_button_new ();
  gtk_widget_show (ExitButton5);
  gtk_fixed_put (GTK_FIXED (fixed24), ExitButton5, 856, 32);
  gtk_widget_set_size_request (ExitButton5, 50, 48);

  image22 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_DND);
  gtk_widget_show (image22);
  gtk_container_add (GTK_CONTAINER (ExitButton5), image22);

  labelEditDate = gtk_label_new (_("Modifier les dates :"));
  gtk_widget_show (labelEditDate);
  gtk_fixed_put (GTK_FIXED (fixed24), labelEditDate, 224, 40);
  gtk_widget_set_size_request (labelEditDate, 472, 80);

  ButtonConfirmEdit = gtk_button_new_with_mnemonic (_("Confirmer"));
  gtk_widget_show (ButtonConfirmEdit);
  gtk_fixed_put (GTK_FIXED (fixed24), ButtonConfirmEdit, 184, 520);
  gtk_widget_set_size_request (ButtonConfirmEdit, 210, 61);

  buttonReturnCal = gtk_button_new_with_mnemonic (_("Retourner au calendrier"));
  gtk_widget_show (buttonReturnCal);
  gtk_fixed_put (GTK_FIXED (fixed24), buttonReturnCal, 480, 520);
  gtk_widget_set_size_request (buttonReturnCal, 232, 64);

  LabelSuccessEdit = gtk_label_new_with_mnemonic (_("<span foreground=\"green\"><b>\303\251l\303\251ment modifi\303\251 avec succ\303\250s !</b></span>"));
  gtk_fixed_put (GTK_FIXED (fixed24), LabelSuccessEdit, 272, 112);
  gtk_widget_set_size_request (LabelSuccessEdit, 376, 48);
  gtk_label_set_use_markup (GTK_LABEL (LabelSuccessEdit), TRUE);
  gtk_label_set_justify (GTK_LABEL (LabelSuccessEdit), GTK_JUSTIFY_CENTER);

  g_signal_connect ((gpointer) ExitButton5, "clicked",
                    G_CALLBACK (on_ExitButton5_clicked),
                    NULL);
  g_signal_connect ((gpointer) ButtonConfirmEdit, "clicked",
                    G_CALLBACK (on_ButtonConfirmEdit_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonReturnCal, "clicked",
                    G_CALLBACK (on_buttonReturnCal_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (EditPlant, EditPlant, "EditPlant");
  GLADE_HOOKUP_OBJECT (EditPlant, fixed24, "fixed24");
  GLADE_HOOKUP_OBJECT (EditPlant, calendarEditPlanting, "calendarEditPlanting");
  GLADE_HOOKUP_OBJECT (EditPlant, calendarEditHarvesting, "calendarEditHarvesting");
  GLADE_HOOKUP_OBJECT (EditPlant, labelEditCal4, "labelEditCal4");
  GLADE_HOOKUP_OBJECT (EditPlant, labelEditCal3, "labelEditCal3");
  GLADE_HOOKUP_OBJECT (EditPlant, ExitButton5, "ExitButton5");
  GLADE_HOOKUP_OBJECT (EditPlant, image22, "image22");
  GLADE_HOOKUP_OBJECT (EditPlant, labelEditDate, "labelEditDate");
  GLADE_HOOKUP_OBJECT (EditPlant, ButtonConfirmEdit, "ButtonConfirmEdit");
  GLADE_HOOKUP_OBJECT (EditPlant, buttonReturnCal, "buttonReturnCal");
  GLADE_HOOKUP_OBJECT (EditPlant, LabelSuccessEdit, "LabelSuccessEdit");

  return EditPlant;
}

