/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_CalendarMain (void);
GtkWidget* create_CheckCalendar (void);
GtkWidget* create_ChoosePlant (void);
GtkWidget* create_EditPlant (void);
