/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_WindowDashboard (void);
GtkWidget* create_WindowGestiondescapteurs (void);
GtkWidget* create_gestionouvriers (void);
GtkWidget* create_gclients (void);
GtkWidget* create_gequipements (void);
GtkWidget* create_gtroupeaux (void);
GtkWidget* create_auth (void);
GtkWidget* create_admin (void);
GtkWidget* create_gutilisateurs (void);
GtkWidget* create_CheckCalendar (void);
GtkWidget* create_CalendarMain (void);
GtkWidget* create_ChoosePlant (void);
GtkWidget* create_EditPlant (void);
