/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_WindowWelcome (void);
GtkWidget* create_WindowInscription (void);
GtkWidget* create_WindowConnexion (void);
GtkWidget* create_WindowProprietaire (void);
GtkWidget* create_WindowGestiondesutilisateurs (void);
GtkWidget* create_WindowUtilisateur (void);
GtkWidget* create_WindowOuvrier (void);
