/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_WindowWelcome (void)
{
  GtkWidget *WindowWelcome;
  GtkWidget *fixed1;
  GtkWidget *ButtonSeConnecter;
  GtkWidget *alignment2;
  GtkWidget *hbox2;
  GtkWidget *image2;
  GtkWidget *label4;
  GtkWidget *ButtonInscrire;
  GtkWidget *alignment1;
  GtkWidget *hbox1;
  GtkWidget *image1;
  GtkWidget *label3;
  GtkWidget *image3;
  GtkWidget *labelwelcome;

  WindowWelcome = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (WindowWelcome), _("WindowWelcome"));

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (WindowWelcome), fixed1);

  ButtonSeConnecter = gtk_button_new ();
  gtk_widget_show (ButtonSeConnecter);
  gtk_fixed_put (GTK_FIXED (fixed1), ButtonSeConnecter, 336, 312);
  gtk_widget_set_size_request (ButtonSeConnecter, 128, 37);

  alignment2 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (ButtonSeConnecter), alignment2);

  hbox2 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox2);
  gtk_container_add (GTK_CONTAINER (alignment2), hbox2);

  image2 = gtk_image_new_from_stock ("gtk-dialog-authentication", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image2);
  gtk_box_pack_start (GTK_BOX (hbox2), image2, FALSE, FALSE, 0);

  label4 = gtk_label_new_with_mnemonic (_("Se Connecter"));
  gtk_widget_show (label4);
  gtk_box_pack_start (GTK_BOX (hbox2), label4, FALSE, FALSE, 0);

  ButtonInscrire = gtk_button_new ();
  gtk_widget_show (ButtonInscrire);
  gtk_fixed_put (GTK_FIXED (fixed1), ButtonInscrire, 336, 264);
  gtk_widget_set_size_request (ButtonInscrire, 128, 37);

  alignment1 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (ButtonInscrire), alignment1);

  hbox1 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox1);
  gtk_container_add (GTK_CONTAINER (alignment1), hbox1);

  image1 = gtk_image_new_from_stock ("gtk-new", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image1);
  gtk_box_pack_start (GTK_BOX (hbox1), image1, FALSE, FALSE, 0);

  label3 = gtk_label_new_with_mnemonic (_("S'inscrire"));
  gtk_widget_show (label3);
  gtk_box_pack_start (GTK_BOX (hbox1), label3, FALSE, FALSE, 0);

  image3 = create_pixmap (WindowWelcome, "SmartFarm_logo.jpeg");
  gtk_widget_show (image3);
  gtk_fixed_put (GTK_FIXED (fixed1), image3, 272, 64);
  gtk_widget_set_size_request (image3, 256, 184);

  labelwelcome = gtk_label_new_with_mnemonic (_("<span foreground=\"green\"><b>WELCOME TO OUR SMARTFARM</b></span>"));
  gtk_widget_show (labelwelcome);
  gtk_fixed_put (GTK_FIXED (fixed1), labelwelcome, 158, 16);
  gtk_widget_set_size_request (labelwelcome, 484, 28);
  gtk_label_set_use_markup (GTK_LABEL (labelwelcome), TRUE);

  g_signal_connect ((gpointer) ButtonSeConnecter, "clicked",
                    G_CALLBACK (on_ButtonSeConnecter_clicked),
                    NULL);
  g_signal_connect ((gpointer) ButtonInscrire, "clicked",
                    G_CALLBACK (on_ButtonInscrire_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (WindowWelcome, WindowWelcome, "WindowWelcome");
  GLADE_HOOKUP_OBJECT (WindowWelcome, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (WindowWelcome, ButtonSeConnecter, "ButtonSeConnecter");
  GLADE_HOOKUP_OBJECT (WindowWelcome, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (WindowWelcome, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (WindowWelcome, image2, "image2");
  GLADE_HOOKUP_OBJECT (WindowWelcome, label4, "label4");
  GLADE_HOOKUP_OBJECT (WindowWelcome, ButtonInscrire, "ButtonInscrire");
  GLADE_HOOKUP_OBJECT (WindowWelcome, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (WindowWelcome, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (WindowWelcome, image1, "image1");
  GLADE_HOOKUP_OBJECT (WindowWelcome, label3, "label3");
  GLADE_HOOKUP_OBJECT (WindowWelcome, image3, "image3");
  GLADE_HOOKUP_OBJECT (WindowWelcome, labelwelcome, "labelwelcome");

  return WindowWelcome;
}

GtkWidget*
create_WindowInscription (void)
{
  GtkWidget *WindowInscription;
  GtkWidget *fixed3;
  GtkWidget *EntryNom;
  GtkWidget *EntryPrenom;
  GtkWidget *EntryUsername;
  GtkWidget *EntryPassword;
  GtkWidget *calendardate;
  GtkWidget *image4;
  GtkWidget *labelinscri;
  GtkWidget *label11;
  GtkWidget *label6;
  GtkWidget *label8;
  GtkWidget *label10;
  GtkWidget *label9;
  GtkWidget *label7;
  GtkWidget *ButtonRetour;
  GtkWidget *alignment4;
  GtkWidget *hbox4;
  GtkWidget *image6;
  GtkWidget *label14;
  GtkWidget *ButtonInscri;
  GtkWidget *alignment3;
  GtkWidget *hbox3;
  GtkWidget *image5;
  GtkWidget *label13;
  GtkWidget *checkbutton1;
  GtkWidget *labelinscriptionerreur;
  GtkWidget *comboboxentryrole;
  GtkWidget *labelinscrit;
  GtkWidget *labelexisteinscrit;

  WindowInscription = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (WindowInscription), _("WindowInscription"));

  fixed3 = gtk_fixed_new ();
  gtk_widget_show (fixed3);
  gtk_container_add (GTK_CONTAINER (WindowInscription), fixed3);

  EntryNom = gtk_entry_new ();
  gtk_widget_show (EntryNom);
  gtk_fixed_put (GTK_FIXED (fixed3), EntryNom, 328, 88);
  gtk_widget_set_size_request (EntryNom, 144, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (EntryNom), 8226);

  EntryPrenom = gtk_entry_new ();
  gtk_widget_show (EntryPrenom);
  gtk_fixed_put (GTK_FIXED (fixed3), EntryPrenom, 328, 144);
  gtk_widget_set_size_request (EntryPrenom, 144, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (EntryPrenom), 8226);

  EntryUsername = gtk_entry_new ();
  gtk_widget_show (EntryUsername);
  gtk_fixed_put (GTK_FIXED (fixed3), EntryUsername, 328, 192);
  gtk_widget_set_size_request (EntryUsername, 144, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (EntryUsername), 8226);

  EntryPassword = gtk_entry_new ();
  gtk_widget_show (EntryPassword);
  gtk_fixed_put (GTK_FIXED (fixed3), EntryPassword, 328, 240);
  gtk_widget_set_size_request (EntryPassword, 144, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (EntryPassword), 8226);

  calendardate = gtk_calendar_new ();
  gtk_widget_show (calendardate);
  gtk_fixed_put (GTK_FIXED (fixed3), calendardate, 632, 80);
  gtk_widget_set_size_request (calendardate, 168, 160);
  gtk_calendar_display_options (GTK_CALENDAR (calendardate),
                                GTK_CALENDAR_SHOW_HEADING
                                | GTK_CALENDAR_SHOW_DAY_NAMES);

  image4 = create_pixmap (WindowInscription, "images.jpeg");
  gtk_widget_show (image4);
  gtk_fixed_put (GTK_FIXED (fixed3), image4, 16, 64);
  gtk_widget_set_size_request (image4, 216, 248);

  labelinscri = gtk_label_new_with_mnemonic (_("<span foreground=\"#83344D\"><b>FORMULAIRE D'INSCRIPTION</b></span>"));
  gtk_widget_show (labelinscri);
  gtk_fixed_put (GTK_FIXED (fixed3), labelinscri, 192, 0);
  gtk_widget_set_size_request (labelinscri, 424, 56);
  gtk_label_set_use_markup (GTK_LABEL (labelinscri), TRUE);

  label11 = gtk_label_new (_("Date de naissance :"));
  gtk_widget_show (label11);
  gtk_fixed_put (GTK_FIXED (fixed3), label11, 472, 64);
  gtk_widget_set_size_request (label11, 144, 41);

  label6 = gtk_label_new (_("Pr\303\251nom :"));
  gtk_widget_show (label6);
  gtk_fixed_put (GTK_FIXED (fixed3), label6, 232, 144);
  gtk_widget_set_size_request (label6, 104, 24);

  label8 = gtk_label_new (_("Username :"));
  gtk_widget_show (label8);
  gtk_fixed_put (GTK_FIXED (fixed3), label8, 232, 193);
  gtk_widget_set_size_request (label8, 96, 23);

  label10 = gtk_label_new (_("Password :"));
  gtk_widget_show (label10);
  gtk_fixed_put (GTK_FIXED (fixed3), label10, 232, 240);
  gtk_widget_set_size_request (label10, 96, 24);

  label9 = gtk_label_new (_("R\303\264le : "));
  gtk_widget_show (label9);
  gtk_fixed_put (GTK_FIXED (fixed3), label9, 544, 248);
  gtk_widget_set_size_request (label9, 80, 32);

  label7 = gtk_label_new (_("Nom :"));
  gtk_widget_show (label7);
  gtk_fixed_put (GTK_FIXED (fixed3), label7, 232, 88);
  gtk_widget_set_size_request (label7, 89, 24);

  ButtonRetour = gtk_button_new ();
  gtk_widget_show (ButtonRetour);
  gtk_fixed_put (GTK_FIXED (fixed3), ButtonRetour, 288, 336);
  gtk_widget_set_size_request (ButtonRetour, 112, 37);

  alignment4 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment4);
  gtk_container_add (GTK_CONTAINER (ButtonRetour), alignment4);

  hbox4 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox4);
  gtk_container_add (GTK_CONTAINER (alignment4), hbox4);

  image6 = gtk_image_new_from_stock ("gtk-media-previous", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image6);
  gtk_box_pack_start (GTK_BOX (hbox4), image6, FALSE, FALSE, 0);

  label14 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label14);
  gtk_box_pack_start (GTK_BOX (hbox4), label14, FALSE, FALSE, 0);

  ButtonInscri = gtk_button_new ();
  gtk_widget_show (ButtonInscri);
  gtk_fixed_put (GTK_FIXED (fixed3), ButtonInscri, 456, 336);
  gtk_widget_set_size_request (ButtonInscri, 136, 37);

  alignment3 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment3);
  gtk_container_add (GTK_CONTAINER (ButtonInscri), alignment3);

  hbox3 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox3);
  gtk_container_add (GTK_CONTAINER (alignment3), hbox3);

  image5 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image5);
  gtk_box_pack_start (GTK_BOX (hbox3), image5, FALSE, FALSE, 0);

  label13 = gtk_label_new_with_mnemonic (_("S'inscrire"));
  gtk_widget_show (label13);
  gtk_box_pack_start (GTK_BOX (hbox3), label13, FALSE, FALSE, 0);

  checkbutton1 = gtk_check_button_new_with_mnemonic (_("Voulez-vous vraiment s'inscrire ?"));
  gtk_widget_show (checkbutton1);
  gtk_fixed_put (GTK_FIXED (fixed3), checkbutton1, 384, 288);
  gtk_widget_set_size_request (checkbutton1, 248, 40);

  labelinscriptionerreur = gtk_label_new_with_mnemonic (_("<span foreground=\"red\"><b>Saisir des donn\303\251es convenables !</b></span>\n"));
  gtk_fixed_put (GTK_FIXED (fixed3), labelinscriptionerreur, 488, 112);
  gtk_widget_set_size_request (labelinscriptionerreur, 112, 120);
  gtk_label_set_use_markup (GTK_LABEL (labelinscriptionerreur), TRUE);
  gtk_label_set_line_wrap (GTK_LABEL (labelinscriptionerreur), TRUE);

  comboboxentryrole = gtk_combo_box_entry_new_text ();
  gtk_widget_show (comboboxentryrole);
  gtk_fixed_put (GTK_FIXED (fixed3), comboboxentryrole, 624, 248);
  gtk_widget_set_size_request (comboboxentryrole, 168, 32);
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryrole), _("Proprietaire"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryrole), _("Utilisateur"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryrole), _("Ouvrier"));

  labelinscrit = gtk_label_new_with_mnemonic (_("<span foreground=\"#169F0B\"><b>Bien inscrit !</b></span>"));
  gtk_fixed_put (GTK_FIXED (fixed3), labelinscrit, 616, 344);
  gtk_widget_set_size_request (labelinscrit, 81, 65);
  gtk_label_set_use_markup (GTK_LABEL (labelinscrit), TRUE);

  labelexisteinscrit = gtk_label_new_with_mnemonic (_("<span foreground=\"red\"><b>D\303\251j\303\240 inscrit !</b></span>\n"));
  gtk_fixed_put (GTK_FIXED (fixed3), labelexisteinscrit, 616, 392);
  gtk_widget_set_size_request (labelexisteinscrit, 112, 17);
  gtk_label_set_use_markup (GTK_LABEL (labelexisteinscrit), TRUE);

  g_signal_connect ((gpointer) ButtonRetour, "clicked",
                    G_CALLBACK (on_ButtonRetour_clicked),
                    NULL);
  g_signal_connect ((gpointer) ButtonInscri, "clicked",
                    G_CALLBACK (on_ButtonInscri_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (WindowInscription, WindowInscription, "WindowInscription");
  GLADE_HOOKUP_OBJECT (WindowInscription, fixed3, "fixed3");
  GLADE_HOOKUP_OBJECT (WindowInscription, EntryNom, "EntryNom");
  GLADE_HOOKUP_OBJECT (WindowInscription, EntryPrenom, "EntryPrenom");
  GLADE_HOOKUP_OBJECT (WindowInscription, EntryUsername, "EntryUsername");
  GLADE_HOOKUP_OBJECT (WindowInscription, EntryPassword, "EntryPassword");
  GLADE_HOOKUP_OBJECT (WindowInscription, calendardate, "calendardate");
  GLADE_HOOKUP_OBJECT (WindowInscription, image4, "image4");
  GLADE_HOOKUP_OBJECT (WindowInscription, labelinscri, "labelinscri");
  GLADE_HOOKUP_OBJECT (WindowInscription, label11, "label11");
  GLADE_HOOKUP_OBJECT (WindowInscription, label6, "label6");
  GLADE_HOOKUP_OBJECT (WindowInscription, label8, "label8");
  GLADE_HOOKUP_OBJECT (WindowInscription, label10, "label10");
  GLADE_HOOKUP_OBJECT (WindowInscription, label9, "label9");
  GLADE_HOOKUP_OBJECT (WindowInscription, label7, "label7");
  GLADE_HOOKUP_OBJECT (WindowInscription, ButtonRetour, "ButtonRetour");
  GLADE_HOOKUP_OBJECT (WindowInscription, alignment4, "alignment4");
  GLADE_HOOKUP_OBJECT (WindowInscription, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (WindowInscription, image6, "image6");
  GLADE_HOOKUP_OBJECT (WindowInscription, label14, "label14");
  GLADE_HOOKUP_OBJECT (WindowInscription, ButtonInscri, "ButtonInscri");
  GLADE_HOOKUP_OBJECT (WindowInscription, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (WindowInscription, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (WindowInscription, image5, "image5");
  GLADE_HOOKUP_OBJECT (WindowInscription, label13, "label13");
  GLADE_HOOKUP_OBJECT (WindowInscription, checkbutton1, "checkbutton1");
  GLADE_HOOKUP_OBJECT (WindowInscription, labelinscriptionerreur, "labelinscriptionerreur");
  GLADE_HOOKUP_OBJECT (WindowInscription, comboboxentryrole, "comboboxentryrole");
  GLADE_HOOKUP_OBJECT (WindowInscription, labelinscrit, "labelinscrit");
  GLADE_HOOKUP_OBJECT (WindowInscription, labelexisteinscrit, "labelexisteinscrit");

  return WindowInscription;
}

GtkWidget*
create_WindowConnexion (void)
{
  GtkWidget *WindowConnexion;
  GtkWidget *fixed4;
  GtkWidget *entryuser;
  GtkWidget *entrypass;
  GtkWidget *image7;
  GtkWidget *label15;
  GtkWidget *label16;
  GtkWidget *label17;
  GtkWidget *Buttonlogin;
  GtkWidget *alignment6;
  GtkWidget *hbox6;
  GtkWidget *image9;
  GtkWidget *label19;
  GtkWidget *checkbutton2;
  GtkWidget *ButtonReturn;
  GtkWidget *alignment5;
  GtkWidget *hbox5;
  GtkWidget *image8;
  GtkWidget *label18;
  GtkWidget *labelfaillogin;

  WindowConnexion = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (WindowConnexion), _("WindowConnexion"));

  fixed4 = gtk_fixed_new ();
  gtk_widget_show (fixed4);
  gtk_container_add (GTK_CONTAINER (WindowConnexion), fixed4);

  entryuser = gtk_entry_new ();
  gtk_widget_show (entryuser);
  gtk_fixed_put (GTK_FIXED (fixed4), entryuser, 544, 120);
  gtk_widget_set_size_request (entryuser, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryuser), 8226);

  entrypass = gtk_entry_new ();
  gtk_widget_show (entrypass);
  gtk_fixed_put (GTK_FIXED (fixed4), entrypass, 544, 168);
  gtk_widget_set_size_request (entrypass, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entrypass), 8226);

  image7 = create_pixmap (WindowConnexion, "authentification.png");
  gtk_widget_show (image7);
  gtk_fixed_put (GTK_FIXED (fixed4), image7, 0, 72);
  gtk_widget_set_size_request (image7, 368, 304);

  label15 = gtk_label_new_with_mnemonic (_("<span foreground=\"#EC7063\"><b>LOG IN TO YOUR PERSONAL SPACE</b></span>\n"));
  gtk_widget_show (label15);
  gtk_fixed_put (GTK_FIXED (fixed4), label15, 216, 0);
  gtk_widget_set_size_request (label15, 416, 65);
  gtk_label_set_use_markup (GTK_LABEL (label15), TRUE);

  label16 = gtk_label_new (_("USERNAME :"));
  gtk_widget_show (label16);
  gtk_fixed_put (GTK_FIXED (fixed4), label16, 416, 120);
  gtk_widget_set_size_request (label16, 128, 24);

  label17 = gtk_label_new (_("PASSWORD :"));
  gtk_widget_show (label17);
  gtk_fixed_put (GTK_FIXED (fixed4), label17, 408, 168);
  gtk_widget_set_size_request (label17, 152, 25);

  Buttonlogin = gtk_button_new ();
  gtk_widget_show (Buttonlogin);
  gtk_fixed_put (GTK_FIXED (fixed4), Buttonlogin, 688, 264);
  gtk_widget_set_size_request (Buttonlogin, 96, 29);

  alignment6 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment6);
  gtk_container_add (GTK_CONTAINER (Buttonlogin), alignment6);

  hbox6 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox6);
  gtk_container_add (GTK_CONTAINER (alignment6), hbox6);

  image9 = gtk_image_new_from_stock ("gtk-dialog-authentication", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image9);
  gtk_box_pack_start (GTK_BOX (hbox6), image9, FALSE, FALSE, 0);

  label19 = gtk_label_new_with_mnemonic (_("Login"));
  gtk_widget_show (label19);
  gtk_box_pack_start (GTK_BOX (hbox6), label19, FALSE, FALSE, 0);

  checkbutton2 = gtk_check_button_new_with_mnemonic (_("Stay Connected"));
  gtk_widget_show (checkbutton2);
  gtk_fixed_put (GTK_FIXED (fixed4), checkbutton2, 640, 216);
  gtk_widget_set_size_request (checkbutton2, 160, 32);

  ButtonReturn = gtk_button_new ();
  gtk_widget_show (ButtonReturn);
  gtk_fixed_put (GTK_FIXED (fixed4), ButtonReturn, 480, 264);
  gtk_widget_set_size_request (ButtonReturn, 88, 29);

  alignment5 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment5);
  gtk_container_add (GTK_CONTAINER (ButtonReturn), alignment5);

  hbox5 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox5);
  gtk_container_add (GTK_CONTAINER (alignment5), hbox5);

  image8 = gtk_image_new_from_stock ("gtk-media-previous", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image8);
  gtk_box_pack_start (GTK_BOX (hbox5), image8, FALSE, FALSE, 0);

  label18 = gtk_label_new_with_mnemonic (_("Return "));
  gtk_widget_show (label18);
  gtk_box_pack_start (GTK_BOX (hbox5), label18, FALSE, FALSE, 0);

  labelfaillogin = gtk_label_new_with_mnemonic (_("<span foreground=\"red\"><b>Ce compte n'existe pas!</b></span>\n"));
  gtk_fixed_put (GTK_FIXED (fixed4), labelfaillogin, 616, 296);
  gtk_widget_set_size_request (labelfaillogin, 216, 25);
  gtk_label_set_use_markup (GTK_LABEL (labelfaillogin), TRUE);

  g_signal_connect ((gpointer) Buttonlogin, "clicked",
                    G_CALLBACK (on_Buttonlogin_clicked),
                    NULL);
  g_signal_connect ((gpointer) ButtonReturn, "clicked",
                    G_CALLBACK (on_ButtonReturn_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (WindowConnexion, WindowConnexion, "WindowConnexion");
  GLADE_HOOKUP_OBJECT (WindowConnexion, fixed4, "fixed4");
  GLADE_HOOKUP_OBJECT (WindowConnexion, entryuser, "entryuser");
  GLADE_HOOKUP_OBJECT (WindowConnexion, entrypass, "entrypass");
  GLADE_HOOKUP_OBJECT (WindowConnexion, image7, "image7");
  GLADE_HOOKUP_OBJECT (WindowConnexion, label15, "label15");
  GLADE_HOOKUP_OBJECT (WindowConnexion, label16, "label16");
  GLADE_HOOKUP_OBJECT (WindowConnexion, label17, "label17");
  GLADE_HOOKUP_OBJECT (WindowConnexion, Buttonlogin, "Buttonlogin");
  GLADE_HOOKUP_OBJECT (WindowConnexion, alignment6, "alignment6");
  GLADE_HOOKUP_OBJECT (WindowConnexion, hbox6, "hbox6");
  GLADE_HOOKUP_OBJECT (WindowConnexion, image9, "image9");
  GLADE_HOOKUP_OBJECT (WindowConnexion, label19, "label19");
  GLADE_HOOKUP_OBJECT (WindowConnexion, checkbutton2, "checkbutton2");
  GLADE_HOOKUP_OBJECT (WindowConnexion, ButtonReturn, "ButtonReturn");
  GLADE_HOOKUP_OBJECT (WindowConnexion, alignment5, "alignment5");
  GLADE_HOOKUP_OBJECT (WindowConnexion, hbox5, "hbox5");
  GLADE_HOOKUP_OBJECT (WindowConnexion, image8, "image8");
  GLADE_HOOKUP_OBJECT (WindowConnexion, label18, "label18");
  GLADE_HOOKUP_OBJECT (WindowConnexion, labelfaillogin, "labelfaillogin");

  return WindowConnexion;
}

GtkWidget*
create_WindowProprietaire (void)
{
  GtkWidget *WindowProprietaire;
  GtkWidget *fixed5;
  GtkWidget *image10;
  GtkWidget *label20;
  GtkWidget *ButtonQuitp;
  GtkWidget *alignment7;
  GtkWidget *hbox7;
  GtkWidget *image11;
  GtkWidget *label21;
  GtkWidget *ButtonGestiondesutilisateurs;
  GtkWidget *ButtonGestiondescapteurs;
  GtkWidget *ButtonGestiondesouvriers;
  GtkWidget *ButtonGestiondesclients;
  GtkWidget *ButtonGestiondestroupeaux;
  GtkWidget *ButtonGestionducalendrier;
  GtkWidget *ButtonGestiondesequipements;

  WindowProprietaire = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (WindowProprietaire), _("WindowProprietaire"));

  fixed5 = gtk_fixed_new ();
  gtk_widget_show (fixed5);
  gtk_container_add (GTK_CONTAINER (WindowProprietaire), fixed5);

  image10 = create_pixmap (WindowProprietaire, "admin.png");
  gtk_widget_show (image10);
  gtk_fixed_put (GTK_FIXED (fixed5), image10, 8, 64);
  gtk_widget_set_size_request (image10, 320, 269);

  label20 = gtk_label_new_with_mnemonic (_("<span foreground=\"red\"><b>ESPACE DU PROPRI\303\211TAIRE</b></span>"));
  gtk_widget_show (label20);
  gtk_fixed_put (GTK_FIXED (fixed5), label20, 72, 0);
  gtk_widget_set_size_request (label20, 680, 56);
  gtk_label_set_use_markup (GTK_LABEL (label20), TRUE);

  ButtonQuitp = gtk_button_new ();
  gtk_widget_show (ButtonQuitp);
  gtk_fixed_put (GTK_FIXED (fixed5), ButtonQuitp, 672, 16);
  gtk_widget_set_size_request (ButtonQuitp, 112, 40);

  alignment7 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment7);
  gtk_container_add (GTK_CONTAINER (ButtonQuitp), alignment7);

  hbox7 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox7);
  gtk_container_add (GTK_CONTAINER (alignment7), hbox7);

  image11 = gtk_image_new_from_stock ("gtk-quit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image11);
  gtk_box_pack_start (GTK_BOX (hbox7), image11, FALSE, FALSE, 0);

  label21 = gtk_label_new_with_mnemonic (_("QUITTER"));
  gtk_widget_show (label21);
  gtk_box_pack_start (GTK_BOX (hbox7), label21, FALSE, FALSE, 0);

  ButtonGestiondesutilisateurs = gtk_button_new_with_mnemonic (_("GESTION DES UTILISATEURS"));
  gtk_widget_show (ButtonGestiondesutilisateurs);
  gtk_fixed_put (GTK_FIXED (fixed5), ButtonGestiondesutilisateurs, 520, 80);
  gtk_widget_set_size_request (ButtonGestiondesutilisateurs, 208, 29);

  ButtonGestiondescapteurs = gtk_button_new_with_mnemonic (_("GESTION DES CAPTEURS"));
  gtk_widget_show (ButtonGestiondescapteurs);
  gtk_fixed_put (GTK_FIXED (fixed5), ButtonGestiondescapteurs, 520, 120);
  gtk_widget_set_size_request (ButtonGestiondescapteurs, 200, 29);

  ButtonGestiondesouvriers = gtk_button_new_with_mnemonic (_("GESTION DES OUVRIERS"));
  gtk_widget_show (ButtonGestiondesouvriers);
  gtk_fixed_put (GTK_FIXED (fixed5), ButtonGestiondesouvriers, 520, 160);
  gtk_widget_set_size_request (ButtonGestiondesouvriers, 200, 29);

  ButtonGestiondesclients = gtk_button_new_with_mnemonic (_("GESTION DES CLIENTS"));
  gtk_widget_show (ButtonGestiondesclients);
  gtk_fixed_put (GTK_FIXED (fixed5), ButtonGestiondesclients, 520, 256);
  gtk_widget_set_size_request (ButtonGestiondesclients, 208, 29);

  ButtonGestiondestroupeaux = gtk_button_new_with_mnemonic (_("GESTION DES TROUPEAUX"));
  gtk_widget_show (ButtonGestiondestroupeaux);
  gtk_fixed_put (GTK_FIXED (fixed5), ButtonGestiondestroupeaux, 528, 296);
  gtk_widget_set_size_request (ButtonGestiondestroupeaux, 200, 29);

  ButtonGestionducalendrier = gtk_button_new_with_mnemonic (_("GESTION DU CALENDRIER"));
  gtk_widget_show (ButtonGestionducalendrier);
  gtk_fixed_put (GTK_FIXED (fixed5), ButtonGestionducalendrier, 528, 344);
  gtk_widget_set_size_request (ButtonGestionducalendrier, 200, 29);

  ButtonGestiondesequipements = gtk_button_new_with_mnemonic (_("GESTION DES \303\211QUIPEMENTS"));
  gtk_widget_show (ButtonGestiondesequipements);
  gtk_fixed_put (GTK_FIXED (fixed5), ButtonGestiondesequipements, 520, 208);
  gtk_widget_set_size_request (ButtonGestiondesequipements, 208, 29);

  g_signal_connect ((gpointer) ButtonQuitp, "clicked",
                    G_CALLBACK (on_ButtonQuitp_clicked),
                    NULL);
  g_signal_connect ((gpointer) ButtonGestiondesutilisateurs, "clicked",
                    G_CALLBACK (on_ButtonGestiondesutilisateurs_clicked),
                    NULL);
  g_signal_connect ((gpointer) ButtonGestiondescapteurs, "clicked",
                    G_CALLBACK (on_ButtonGestiondescapteurs_clicked),
                    NULL);
  g_signal_connect ((gpointer) ButtonGestiondesouvriers, "clicked",
                    G_CALLBACK (on_ButtonGestiondesouvriers_clicked),
                    NULL);
  g_signal_connect ((gpointer) ButtonGestiondesclients, "clicked",
                    G_CALLBACK (on_ButtonGestiondesclients_clicked),
                    NULL);
  g_signal_connect ((gpointer) ButtonGestiondestroupeaux, "clicked",
                    G_CALLBACK (on_ButtonGestiondestroupeaux_clicked),
                    NULL);
  g_signal_connect ((gpointer) ButtonGestionducalendrier, "clicked",
                    G_CALLBACK (on_ButtonGestionducalendrier_clicked),
                    NULL);
  g_signal_connect ((gpointer) ButtonGestiondesequipements, "clicked",
                    G_CALLBACK (on_ButtonGestiondesequipements_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (WindowProprietaire, WindowProprietaire, "WindowProprietaire");
  GLADE_HOOKUP_OBJECT (WindowProprietaire, fixed5, "fixed5");
  GLADE_HOOKUP_OBJECT (WindowProprietaire, image10, "image10");
  GLADE_HOOKUP_OBJECT (WindowProprietaire, label20, "label20");
  GLADE_HOOKUP_OBJECT (WindowProprietaire, ButtonQuitp, "ButtonQuitp");
  GLADE_HOOKUP_OBJECT (WindowProprietaire, alignment7, "alignment7");
  GLADE_HOOKUP_OBJECT (WindowProprietaire, hbox7, "hbox7");
  GLADE_HOOKUP_OBJECT (WindowProprietaire, image11, "image11");
  GLADE_HOOKUP_OBJECT (WindowProprietaire, label21, "label21");
  GLADE_HOOKUP_OBJECT (WindowProprietaire, ButtonGestiondesutilisateurs, "ButtonGestiondesutilisateurs");
  GLADE_HOOKUP_OBJECT (WindowProprietaire, ButtonGestiondescapteurs, "ButtonGestiondescapteurs");
  GLADE_HOOKUP_OBJECT (WindowProprietaire, ButtonGestiondesouvriers, "ButtonGestiondesouvriers");
  GLADE_HOOKUP_OBJECT (WindowProprietaire, ButtonGestiondesclients, "ButtonGestiondesclients");
  GLADE_HOOKUP_OBJECT (WindowProprietaire, ButtonGestiondestroupeaux, "ButtonGestiondestroupeaux");
  GLADE_HOOKUP_OBJECT (WindowProprietaire, ButtonGestionducalendrier, "ButtonGestionducalendrier");
  GLADE_HOOKUP_OBJECT (WindowProprietaire, ButtonGestiondesequipements, "ButtonGestiondesequipements");

  return WindowProprietaire;
}

GtkWidget*
create_WindowGestiondesutilisateurs (void)
{
  GtkWidget *WindowGestiondesutilisateurs;
  GtkWidget *fixed6;
  GtkWidget *label33;
  GtkWidget *notebook1;
  GtkWidget *fixed9;
  GtkWidget *entrynomutil;
  GtkWidget *entryprenomutil;
  GtkObject *spinbuttonutil_adj;
  GtkWidget *spinbuttonutil;
  GtkWidget *calendarutilisateur;
  GtkWidget *image16;
  GtkWidget *entrycinutil;
  GtkWidget *label36;
  GtkWidget *labelcin;
  GtkWidget *label34;
  GtkWidget *label35;
  GtkWidget *labelnomuti;
  GtkWidget *image17;
  GtkWidget *labelprenomutil;
  GtkWidget *label37;
  GtkWidget *label38;
  GtkWidget *labelverifutil;
  GtkWidget *labelsuccess;
  GtkWidget *labelexiste;
  GtkWidget *label51;
  GtkWidget *buttonAjoututil;
  GtkWidget *alignment10;
  GtkWidget *hbox10;
  GtkWidget *image21;
  GtkWidget *label53;
  GtkWidget *label31;
  GtkWidget *fixed10;
  GtkWidget *treeviewutil;
  GtkWidget *entrycinutilrecherche;
  GtkWidget *label43;
  GtkWidget *image18;
  GtkWidget *ButtonSupprimer;
  GtkWidget *alignment12;
  GtkWidget *hbox12;
  GtkWidget *image23;
  GtkWidget *label55;
  GtkWidget *checkbutton3;
  GtkWidget *image20;
  GtkWidget *label45;
  GtkWidget *labelfailsupp;
  GtkWidget *labelsuccesssup;
  GtkWidget *label44;
  GtkWidget *image19;
  GtkWidget *label56;
  GtkWidget *buttonrecherche;
  GtkWidget *alignment13;
  GtkWidget *hbox13;
  GtkWidget *image24;
  GtkWidget *label57;
  GtkWidget *labelerreur;
  GtkWidget *labeltrouve;
  GtkWidget *label32;
  GtkWidget *buttonQuitutilisateur;
  GtkWidget *alignment11;
  GtkWidget *hbox11;
  GtkWidget *image22;
  GtkWidget *label54;

  WindowGestiondesutilisateurs = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (WindowGestiondesutilisateurs), _("WindowGestiondesutilisateurs"));

  fixed6 = gtk_fixed_new ();
  gtk_widget_show (fixed6);
  gtk_container_add (GTK_CONTAINER (WindowGestiondesutilisateurs), fixed6);

  label33 = gtk_label_new (_("BIENVENU(E) \303\200 L'ESPACE DE GESTION DES UTILISATEURS"));
  gtk_widget_show (label33);
  gtk_fixed_put (GTK_FIXED (fixed6), label33, 72, -16);
  gtk_widget_set_size_request (label33, 600, 65);

  notebook1 = gtk_notebook_new ();
  gtk_widget_show (notebook1);
  gtk_fixed_put (GTK_FIXED (fixed6), notebook1, 0, 40);
  gtk_widget_set_size_request (notebook1, 840, 416);

  fixed9 = gtk_fixed_new ();
  gtk_widget_show (fixed9);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed9);

  entrynomutil = gtk_entry_new ();
  gtk_widget_show (entrynomutil);
  gtk_fixed_put (GTK_FIXED (fixed9), entrynomutil, 192, 96);
  gtk_widget_set_size_request (entrynomutil, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entrynomutil), 8226);

  entryprenomutil = gtk_entry_new ();
  gtk_widget_show (entryprenomutil);
  gtk_fixed_put (GTK_FIXED (fixed9), entryprenomutil, 192, 128);
  gtk_widget_set_size_request (entryprenomutil, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryprenomutil), 8226);

  spinbuttonutil_adj = gtk_adjustment_new (20, 20, 60, 1, 10, 10);
  spinbuttonutil = gtk_spin_button_new (GTK_ADJUSTMENT (spinbuttonutil_adj), 1, 0);
  gtk_widget_show (spinbuttonutil);
  gtk_fixed_put (GTK_FIXED (fixed9), spinbuttonutil, 192, 168);
  gtk_widget_set_size_request (spinbuttonutil, 60, 27);

  calendarutilisateur = gtk_calendar_new ();
  gtk_widget_show (calendarutilisateur);
  gtk_fixed_put (GTK_FIXED (fixed9), calendarutilisateur, 192, 208);
  gtk_widget_set_size_request (calendarutilisateur, 168, 160);
  gtk_calendar_display_options (GTK_CALENDAR (calendarutilisateur),
                                GTK_CALENDAR_SHOW_HEADING
                                | GTK_CALENDAR_SHOW_DAY_NAMES);

  image16 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image16);
  gtk_fixed_put (GTK_FIXED (fixed9), image16, 280, 24);
  gtk_widget_set_size_request (image16, 24, 16);

  entrycinutil = gtk_entry_new ();
  gtk_widget_show (entrycinutil);
  gtk_fixed_put (GTK_FIXED (fixed9), entrycinutil, 192, 64);
  gtk_widget_set_size_request (entrycinutil, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entrycinutil), 8226);

  label36 = gtk_label_new (_("AJOUT D'UN UTILISATEUR"));
  gtk_widget_show (label36);
  gtk_fixed_put (GTK_FIXED (fixed9), label36, 296, 16);
  gtk_widget_set_size_request (label36, 184, 32);

  labelcin = gtk_label_new_with_mnemonic (_("<span foreground=\"red\"><b>Veuillez saisir Cin de l'utilisateur !</b></span>\n"));
  gtk_fixed_put (GTK_FIXED (fixed9), labelcin, 344, 64);
  gtk_widget_set_size_request (labelcin, 264, 24);
  gtk_label_set_use_markup (GTK_LABEL (labelcin), TRUE);

  label34 = gtk_label_new (_("Nom :"));
  gtk_widget_show (label34);
  gtk_fixed_put (GTK_FIXED (fixed9), label34, 104, 96);
  gtk_widget_set_size_request (label34, 128, 25);

  label35 = gtk_label_new (_("Pr\303\251nom :"));
  gtk_widget_show (label35);
  gtk_fixed_put (GTK_FIXED (fixed9), label35, 96, 136);
  gtk_widget_set_size_request (label35, 120, 24);

  labelnomuti = gtk_label_new_with_mnemonic (_("<span foreground=\"red\"><b>Veuillez saisir le nom de l'utilisateur !</b></span>\n"));
  gtk_fixed_put (GTK_FIXED (fixed9), labelnomuti, 352, 96);
  gtk_widget_set_size_request (labelnomuti, 280, 25);
  gtk_label_set_use_markup (GTK_LABEL (labelnomuti), TRUE);

  image17 = create_pixmap (WindowGestiondesutilisateurs, "Avatar_Header.png");
  gtk_widget_show (image17);
  gtk_fixed_put (GTK_FIXED (fixed9), image17, 656, 16);
  gtk_widget_set_size_request (image17, 176, 184);

  labelprenomutil = gtk_label_new_with_mnemonic (_("<span foreground=\"red\"><b>Veuillez saisir le pr\303\251nom de l'utilisateur !</b></span>\n"));
  gtk_fixed_put (GTK_FIXED (fixed9), labelprenomutil, 352, 128);
  gtk_widget_set_size_request (labelprenomutil, 304, 25);
  gtk_label_set_use_markup (GTK_LABEL (labelprenomutil), TRUE);

  label37 = gtk_label_new (_("\303\202ge : "));
  gtk_widget_show (label37);
  gtk_fixed_put (GTK_FIXED (fixed9), label37, 104, 168);
  gtk_widget_set_size_request (label37, 120, 24);

  label38 = gtk_label_new (_("Date de naissance :"));
  gtk_widget_show (label38);
  gtk_fixed_put (GTK_FIXED (fixed9), label38, 24, 192);
  gtk_widget_set_size_request (label38, 184, 41);

  labelverifutil = gtk_label_new_with_mnemonic (_("<span foreground=\"red\"><b>Saisir des donn\303\251es convenables !</b></span>\n"));
  gtk_fixed_put (GTK_FIXED (fixed9), labelverifutil, 368, 160);
  gtk_widget_set_size_request (labelverifutil, 321, 65);
  gtk_label_set_use_markup (GTK_LABEL (labelverifutil), TRUE);

  labelsuccess = gtk_label_new_with_mnemonic (_("<span foreground=\"green\"><b>Utilisateur ajout\303\251 avec succ\303\250s!</b></span>\n"));
  gtk_fixed_put (GTK_FIXED (fixed9), labelsuccess, 400, 200);
  gtk_widget_set_size_request (labelsuccess, 240, 17);
  gtk_label_set_use_markup (GTK_LABEL (labelsuccess), TRUE);

  labelexiste = gtk_label_new_with_mnemonic (_("<span foreground=\"blue\"><b>Utilisateur existe d\303\251j\303\240! </b></span>\n"));
  gtk_fixed_put (GTK_FIXED (fixed9), labelexiste, 424, 216);
  gtk_widget_set_size_request (labelexiste, 200, 41);
  gtk_label_set_use_markup (GTK_LABEL (labelexiste), TRUE);

  label51 = gtk_label_new (_("Cin :"));
  gtk_widget_show (label51);
  gtk_fixed_put (GTK_FIXED (fixed9), label51, 96, 64);
  gtk_widget_set_size_request (label51, 145, 25);

  buttonAjoututil = gtk_button_new ();
  gtk_widget_show (buttonAjoututil);
  gtk_fixed_put (GTK_FIXED (fixed9), buttonAjoututil, 528, 256);
  gtk_widget_set_size_request (buttonAjoututil, 104, 29);

  alignment10 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment10);
  gtk_container_add (GTK_CONTAINER (buttonAjoututil), alignment10);

  hbox10 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox10);
  gtk_container_add (GTK_CONTAINER (alignment10), hbox10);

  image21 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image21);
  gtk_box_pack_start (GTK_BOX (hbox10), image21, FALSE, FALSE, 0);

  label53 = gtk_label_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (label53);
  gtk_box_pack_start (GTK_BOX (hbox10), label53, FALSE, FALSE, 0);

  label31 = gtk_label_new (_("Ajouter"));
  gtk_widget_show (label31);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 0), label31);

  fixed10 = gtk_fixed_new ();
  gtk_widget_show (fixed10);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed10);

  treeviewutil = gtk_tree_view_new ();
  gtk_widget_show (treeviewutil);
  gtk_fixed_put (GTK_FIXED (fixed10), treeviewutil, 16, 40);
  gtk_widget_set_size_request (treeviewutil, 380, 224);

  entrycinutilrecherche = gtk_entry_new ();
  gtk_widget_show (entrycinutilrecherche);
  gtk_fixed_put (GTK_FIXED (fixed10), entrycinutilrecherche, 504, 208);
  gtk_widget_set_size_request (entrycinutilrecherche, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entrycinutilrecherche), 8226);

  label43 = gtk_label_new (_("SUPPRESSION D'UN UTILISATEUR"));
  gtk_widget_show (label43);
  gtk_fixed_put (GTK_FIXED (fixed10), label43, 536, 16);
  gtk_widget_set_size_request (label43, 248, 17);

  image18 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image18);
  gtk_fixed_put (GTK_FIXED (fixed10), image18, 528, 16);
  gtk_widget_set_size_request (image18, 16, 16);

  ButtonSupprimer = gtk_button_new ();
  gtk_widget_show (ButtonSupprimer);
  gtk_fixed_put (GTK_FIXED (fixed10), ButtonSupprimer, 672, 72);
  gtk_widget_set_size_request (ButtonSupprimer, 104, 29);

  alignment12 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment12);
  gtk_container_add (GTK_CONTAINER (ButtonSupprimer), alignment12);

  hbox12 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox12);
  gtk_container_add (GTK_CONTAINER (alignment12), hbox12);

  image23 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image23);
  gtk_box_pack_start (GTK_BOX (hbox12), image23, FALSE, FALSE, 0);

  label55 = gtk_label_new_with_mnemonic (_("Supprimer"));
  gtk_widget_show (label55);
  gtk_box_pack_start (GTK_BOX (hbox12), label55, FALSE, FALSE, 0);

  checkbutton3 = gtk_check_button_new_with_mnemonic (_("Voulez-vous vraiment supprimer cet utilisateur ?"));
  gtk_widget_show (checkbutton3);
  gtk_fixed_put (GTK_FIXED (fixed10), checkbutton3, 456, 40);
  gtk_widget_set_size_request (checkbutton3, 360, 32);

  image20 = gtk_image_new_from_stock ("gtk-info", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image20);
  gtk_fixed_put (GTK_FIXED (fixed10), image20, 40, 16);
  gtk_widget_set_size_request (image20, 21, 21);

  label45 = gtk_label_new (_("AFFICHAGE DE LA LISTE DES UTILISATEURS"));
  gtk_widget_show (label45);
  gtk_fixed_put (GTK_FIXED (fixed10), label45, 56, 16);
  gtk_widget_set_size_request (label45, 304, 17);

  labelfailsupp = gtk_label_new_with_mnemonic (_("<span foreground=\"red\"><b>Utilisateur non supprim\303\251! Veuillez s\303\251lectionner une ligne ! </b></span>\n"));
  gtk_fixed_put (GTK_FIXED (fixed10), labelfailsupp, 408, 104);
  gtk_widget_set_size_request (labelfailsupp, 432, 25);
  gtk_label_set_use_markup (GTK_LABEL (labelfailsupp), TRUE);

  labelsuccesssup = gtk_label_new_with_mnemonic (_("<span foreground=\"green\"><b>Utilisateur bien supprim\303\251!</b></span>\n"));
  gtk_fixed_put (GTK_FIXED (fixed10), labelsuccesssup, 520, 136);
  gtk_widget_set_size_request (labelsuccesssup, 201, 17);
  gtk_label_set_use_markup (GTK_LABEL (labelsuccesssup), TRUE);

  label44 = gtk_label_new (_("RECHERCHE D'UN UTILISATEUR"));
  gtk_widget_show (label44);
  gtk_fixed_put (GTK_FIXED (fixed10), label44, 576, 168);
  gtk_widget_set_size_request (label44, 224, 24);

  image19 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image19);
  gtk_fixed_put (GTK_FIXED (fixed10), image19, 560, 173);
  gtk_widget_set_size_request (image19, 16, 16);

  label56 = gtk_label_new (_("Cin :"));
  gtk_widget_show (label56);
  gtk_fixed_put (GTK_FIXED (fixed10), label56, 440, 208);
  gtk_widget_set_size_request (label56, 57, 25);

  buttonrecherche = gtk_button_new ();
  gtk_widget_show (buttonrecherche);
  gtk_fixed_put (GTK_FIXED (fixed10), buttonrecherche, 688, 208);
  gtk_widget_set_size_request (buttonrecherche, 104, 29);

  alignment13 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment13);
  gtk_container_add (GTK_CONTAINER (buttonrecherche), alignment13);

  hbox13 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox13);
  gtk_container_add (GTK_CONTAINER (alignment13), hbox13);

  image24 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image24);
  gtk_box_pack_start (GTK_BOX (hbox13), image24, FALSE, FALSE, 0);

  label57 = gtk_label_new_with_mnemonic (_("Chercher"));
  gtk_widget_show (label57);
  gtk_box_pack_start (GTK_BOX (hbox13), label57, FALSE, FALSE, 0);

  labelerreur = gtk_label_new_with_mnemonic (_("<span foreground=\"red\"><b>Veuillez saisir Cin de l'utilisateur! </b></span>\n"));
  gtk_fixed_put (GTK_FIXED (fixed10), labelerreur, 448, 248);
  gtk_widget_set_size_request (labelerreur, 392, 17);
  gtk_label_set_use_markup (GTK_LABEL (labelerreur), TRUE);

  labeltrouve = gtk_label_new_with_mnemonic (_("<span foreground=\"orange\"><b>Si l'utilisateur existe il apparait sinon il n'apparait pas</b></span>\n"));
  gtk_fixed_put (GTK_FIXED (fixed10), labeltrouve, 432, 264);
  gtk_widget_set_size_request (labeltrouve, 392, 49);
  gtk_label_set_use_markup (GTK_LABEL (labeltrouve), TRUE);

  label32 = gtk_label_new (_("Afficher/Supprimer/Rechercher"));
  gtk_widget_show (label32);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 1), label32);

  buttonQuitutilisateur = gtk_button_new ();
  gtk_widget_show (buttonQuitutilisateur);
  gtk_fixed_put (GTK_FIXED (fixed6), buttonQuitutilisateur, 656, 0);
  gtk_widget_set_size_request (buttonQuitutilisateur, 104, 37);
  gtk_button_set_focus_on_click (GTK_BUTTON (buttonQuitutilisateur), FALSE);

  alignment11 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment11);
  gtk_container_add (GTK_CONTAINER (buttonQuitutilisateur), alignment11);

  hbox11 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox11);
  gtk_container_add (GTK_CONTAINER (alignment11), hbox11);

  image22 = gtk_image_new_from_stock ("gtk-quit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image22);
  gtk_box_pack_start (GTK_BOX (hbox11), image22, FALSE, FALSE, 0);

  label54 = gtk_label_new_with_mnemonic (_("Quitter"));
  gtk_widget_show (label54);
  gtk_box_pack_start (GTK_BOX (hbox11), label54, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) buttonAjoututil, "clicked",
                    G_CALLBACK (on_buttonAjoututil_clicked),
                    NULL);
  g_signal_connect ((gpointer) treeviewutil, "row_activated",
                    G_CALLBACK (on_treeviewutil_row_activated),
                    NULL);
  g_signal_connect ((gpointer) ButtonSupprimer, "clicked",
                    G_CALLBACK (on_ButtonSupprimer_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonrecherche, "clicked",
                    G_CALLBACK (on_buttonrecherche_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonQuitutilisateur, "clicked",
                    G_CALLBACK (on_buttonQuitutilisateur_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (WindowGestiondesutilisateurs, WindowGestiondesutilisateurs, "WindowGestiondesutilisateurs");
  GLADE_HOOKUP_OBJECT (WindowGestiondesutilisateurs, fixed6, "fixed6");
  GLADE_HOOKUP_OBJECT (WindowGestiondesutilisateurs, label33, "label33");
  GLADE_HOOKUP_OBJECT (WindowGestiondesutilisateurs, notebook1, "notebook1");
  GLADE_HOOKUP_OBJECT (WindowGestiondesutilisateurs, fixed9, "fixed9");
  GLADE_HOOKUP_OBJECT (WindowGestiondesutilisateurs, entrynomutil, "entrynomutil");
  GLADE_HOOKUP_OBJECT (WindowGestiondesutilisateurs, entryprenomutil, "entryprenomutil");
  GLADE_HOOKUP_OBJECT (WindowGestiondesutilisateurs, spinbuttonutil, "spinbuttonutil");
  GLADE_HOOKUP_OBJECT (WindowGestiondesutilisateurs, calendarutilisateur, "calendarutilisateur");
  GLADE_HOOKUP_OBJECT (WindowGestiondesutilisateurs, image16, "image16");
  GLADE_HOOKUP_OBJECT (WindowGestiondesutilisateurs, entrycinutil, "entrycinutil");
  GLADE_HOOKUP_OBJECT (WindowGestiondesutilisateurs, label36, "label36");
  GLADE_HOOKUP_OBJECT (WindowGestiondesutilisateurs, labelcin, "labelcin");
  GLADE_HOOKUP_OBJECT (WindowGestiondesutilisateurs, label34, "label34");
  GLADE_HOOKUP_OBJECT (WindowGestiondesutilisateurs, label35, "label35");
  GLADE_HOOKUP_OBJECT (WindowGestiondesutilisateurs, labelnomuti, "labelnomuti");
  GLADE_HOOKUP_OBJECT (WindowGestiondesutilisateurs, image17, "image17");
  GLADE_HOOKUP_OBJECT (WindowGestiondesutilisateurs, labelprenomutil, "labelprenomutil");
  GLADE_HOOKUP_OBJECT (WindowGestiondesutilisateurs, label37, "label37");
  GLADE_HOOKUP_OBJECT (WindowGestiondesutilisateurs, label38, "label38");
  GLADE_HOOKUP_OBJECT (WindowGestiondesutilisateurs, labelverifutil, "labelverifutil");
  GLADE_HOOKUP_OBJECT (WindowGestiondesutilisateurs, labelsuccess, "labelsuccess");
  GLADE_HOOKUP_OBJECT (WindowGestiondesutilisateurs, labelexiste, "labelexiste");
  GLADE_HOOKUP_OBJECT (WindowGestiondesutilisateurs, label51, "label51");
  GLADE_HOOKUP_OBJECT (WindowGestiondesutilisateurs, buttonAjoututil, "buttonAjoututil");
  GLADE_HOOKUP_OBJECT (WindowGestiondesutilisateurs, alignment10, "alignment10");
  GLADE_HOOKUP_OBJECT (WindowGestiondesutilisateurs, hbox10, "hbox10");
  GLADE_HOOKUP_OBJECT (WindowGestiondesutilisateurs, image21, "image21");
  GLADE_HOOKUP_OBJECT (WindowGestiondesutilisateurs, label53, "label53");
  GLADE_HOOKUP_OBJECT (WindowGestiondesutilisateurs, label31, "label31");
  GLADE_HOOKUP_OBJECT (WindowGestiondesutilisateurs, fixed10, "fixed10");
  GLADE_HOOKUP_OBJECT (WindowGestiondesutilisateurs, treeviewutil, "treeviewutil");
  GLADE_HOOKUP_OBJECT (WindowGestiondesutilisateurs, entrycinutilrecherche, "entrycinutilrecherche");
  GLADE_HOOKUP_OBJECT (WindowGestiondesutilisateurs, label43, "label43");
  GLADE_HOOKUP_OBJECT (WindowGestiondesutilisateurs, image18, "image18");
  GLADE_HOOKUP_OBJECT (WindowGestiondesutilisateurs, ButtonSupprimer, "ButtonSupprimer");
  GLADE_HOOKUP_OBJECT (WindowGestiondesutilisateurs, alignment12, "alignment12");
  GLADE_HOOKUP_OBJECT (WindowGestiondesutilisateurs, hbox12, "hbox12");
  GLADE_HOOKUP_OBJECT (WindowGestiondesutilisateurs, image23, "image23");
  GLADE_HOOKUP_OBJECT (WindowGestiondesutilisateurs, label55, "label55");
  GLADE_HOOKUP_OBJECT (WindowGestiondesutilisateurs, checkbutton3, "checkbutton3");
  GLADE_HOOKUP_OBJECT (WindowGestiondesutilisateurs, image20, "image20");
  GLADE_HOOKUP_OBJECT (WindowGestiondesutilisateurs, label45, "label45");
  GLADE_HOOKUP_OBJECT (WindowGestiondesutilisateurs, labelfailsupp, "labelfailsupp");
  GLADE_HOOKUP_OBJECT (WindowGestiondesutilisateurs, labelsuccesssup, "labelsuccesssup");
  GLADE_HOOKUP_OBJECT (WindowGestiondesutilisateurs, label44, "label44");
  GLADE_HOOKUP_OBJECT (WindowGestiondesutilisateurs, image19, "image19");
  GLADE_HOOKUP_OBJECT (WindowGestiondesutilisateurs, label56, "label56");
  GLADE_HOOKUP_OBJECT (WindowGestiondesutilisateurs, buttonrecherche, "buttonrecherche");
  GLADE_HOOKUP_OBJECT (WindowGestiondesutilisateurs, alignment13, "alignment13");
  GLADE_HOOKUP_OBJECT (WindowGestiondesutilisateurs, hbox13, "hbox13");
  GLADE_HOOKUP_OBJECT (WindowGestiondesutilisateurs, image24, "image24");
  GLADE_HOOKUP_OBJECT (WindowGestiondesutilisateurs, label57, "label57");
  GLADE_HOOKUP_OBJECT (WindowGestiondesutilisateurs, labelerreur, "labelerreur");
  GLADE_HOOKUP_OBJECT (WindowGestiondesutilisateurs, labeltrouve, "labeltrouve");
  GLADE_HOOKUP_OBJECT (WindowGestiondesutilisateurs, label32, "label32");
  GLADE_HOOKUP_OBJECT (WindowGestiondesutilisateurs, buttonQuitutilisateur, "buttonQuitutilisateur");
  GLADE_HOOKUP_OBJECT (WindowGestiondesutilisateurs, alignment11, "alignment11");
  GLADE_HOOKUP_OBJECT (WindowGestiondesutilisateurs, hbox11, "hbox11");
  GLADE_HOOKUP_OBJECT (WindowGestiondesutilisateurs, image22, "image22");
  GLADE_HOOKUP_OBJECT (WindowGestiondesutilisateurs, label54, "label54");

  return WindowGestiondesutilisateurs;
}

GtkWidget*
create_WindowUtilisateur (void)
{
  GtkWidget *WindowUtilisateur;
  GtkWidget *fixed7;
  GtkWidget *image12;
  GtkWidget *label22;
  GtkWidget *buttonGestiondescapteurs;
  GtkWidget *buttonGestiondesouvriers;
  GtkWidget *buttonGestiondesclients;
  GtkWidget *buttonGestiondestroupeaux;
  GtkWidget *buttonGestionducalendrier;
  GtkWidget *ButtonQuitu;
  GtkWidget *alignment8;
  GtkWidget *hbox8;
  GtkWidget *image13;
  GtkWidget *label23;
  GtkWidget *buttonGestiondesequipements;

  WindowUtilisateur = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (WindowUtilisateur), _("WindowUtilisateur"));

  fixed7 = gtk_fixed_new ();
  gtk_widget_show (fixed7);
  gtk_container_add (GTK_CONTAINER (WindowUtilisateur), fixed7);

  image12 = create_pixmap (WindowUtilisateur, "Avatar_Header.png");
  gtk_widget_show (image12);
  gtk_fixed_put (GTK_FIXED (fixed7), image12, 48, 24);
  gtk_widget_set_size_request (image12, 296, 312);

  label22 = gtk_label_new_with_mnemonic (_("<span foreground=\"#1D8348\"><b>ESPACE UTILISATEUR</b></span>"));
  gtk_widget_show (label22);
  gtk_fixed_put (GTK_FIXED (fixed7), label22, 272, 8);
  gtk_widget_set_size_request (label22, 248, 65);
  gtk_label_set_use_markup (GTK_LABEL (label22), TRUE);

  buttonGestiondescapteurs = gtk_button_new_with_mnemonic (_("GESTION DES CAPTEURS"));
  gtk_widget_show (buttonGestiondescapteurs);
  gtk_fixed_put (GTK_FIXED (fixed7), buttonGestiondescapteurs, 456, 104);
  gtk_widget_set_size_request (buttonGestiondescapteurs, 200, 32);

  buttonGestiondesouvriers = gtk_button_new_with_mnemonic (_("GESTION DES OUVRIERS"));
  gtk_widget_show (buttonGestiondesouvriers);
  gtk_fixed_put (GTK_FIXED (fixed7), buttonGestiondesouvriers, 456, 144);
  gtk_widget_set_size_request (buttonGestiondesouvriers, 200, 32);

  buttonGestiondesclients = gtk_button_new_with_mnemonic (_("GESTION DES CLIENTS"));
  gtk_widget_show (buttonGestiondesclients);
  gtk_fixed_put (GTK_FIXED (fixed7), buttonGestiondesclients, 456, 224);
  gtk_widget_set_size_request (buttonGestiondesclients, 208, 32);

  buttonGestiondestroupeaux = gtk_button_new_with_mnemonic (_("GESTION DES TROUPEAUX"));
  gtk_widget_show (buttonGestiondestroupeaux);
  gtk_fixed_put (GTK_FIXED (fixed7), buttonGestiondestroupeaux, 456, 264);
  gtk_widget_set_size_request (buttonGestiondestroupeaux, 208, 29);

  buttonGestionducalendrier = gtk_button_new_with_mnemonic (_("GESTION DU CALENDRIER"));
  gtk_widget_show (buttonGestionducalendrier);
  gtk_fixed_put (GTK_FIXED (fixed7), buttonGestionducalendrier, 456, 304);
  gtk_widget_set_size_request (buttonGestionducalendrier, 208, 29);

  ButtonQuitu = gtk_button_new ();
  gtk_widget_show (ButtonQuitu);
  gtk_fixed_put (GTK_FIXED (fixed7), ButtonQuitu, 696, 24);
  gtk_widget_set_size_request (ButtonQuitu, 114, 37);

  alignment8 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment8);
  gtk_container_add (GTK_CONTAINER (ButtonQuitu), alignment8);

  hbox8 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox8);
  gtk_container_add (GTK_CONTAINER (alignment8), hbox8);

  image13 = gtk_image_new_from_stock ("gtk-quit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image13);
  gtk_box_pack_start (GTK_BOX (hbox8), image13, FALSE, FALSE, 0);

  label23 = gtk_label_new_with_mnemonic (_("Quitter"));
  gtk_widget_show (label23);
  gtk_box_pack_start (GTK_BOX (hbox8), label23, FALSE, FALSE, 0);

  buttonGestiondesequipements = gtk_button_new_with_mnemonic (_("GESTION DES \303\211QUIPEMENTS"));
  gtk_widget_show (buttonGestiondesequipements);
  gtk_fixed_put (GTK_FIXED (fixed7), buttonGestiondesequipements, 456, 184);
  gtk_widget_set_size_request (buttonGestiondesequipements, 208, 32);

  g_signal_connect ((gpointer) buttonGestiondescapteurs, "clicked",
                    G_CALLBACK (on_buttonGestiondescapteurs_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonGestiondesouvriers, "clicked",
                    G_CALLBACK (on_buttonGestiondesouvriers_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonGestiondesclients, "clicked",
                    G_CALLBACK (on_buttonGestiondesclients_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonGestiondestroupeaux, "clicked",
                    G_CALLBACK (on_buttonGestiondestroupeaux_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonGestionducalendrier, "clicked",
                    G_CALLBACK (on_buttonGestionducalendrier_clicked),
                    NULL);
  g_signal_connect ((gpointer) ButtonQuitu, "clicked",
                    G_CALLBACK (on_ButtonQuitu_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonGestiondesequipements, "clicked",
                    G_CALLBACK (on_buttonGestiondesequipements_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (WindowUtilisateur, WindowUtilisateur, "WindowUtilisateur");
  GLADE_HOOKUP_OBJECT (WindowUtilisateur, fixed7, "fixed7");
  GLADE_HOOKUP_OBJECT (WindowUtilisateur, image12, "image12");
  GLADE_HOOKUP_OBJECT (WindowUtilisateur, label22, "label22");
  GLADE_HOOKUP_OBJECT (WindowUtilisateur, buttonGestiondescapteurs, "buttonGestiondescapteurs");
  GLADE_HOOKUP_OBJECT (WindowUtilisateur, buttonGestiondesouvriers, "buttonGestiondesouvriers");
  GLADE_HOOKUP_OBJECT (WindowUtilisateur, buttonGestiondesclients, "buttonGestiondesclients");
  GLADE_HOOKUP_OBJECT (WindowUtilisateur, buttonGestiondestroupeaux, "buttonGestiondestroupeaux");
  GLADE_HOOKUP_OBJECT (WindowUtilisateur, buttonGestionducalendrier, "buttonGestionducalendrier");
  GLADE_HOOKUP_OBJECT (WindowUtilisateur, ButtonQuitu, "ButtonQuitu");
  GLADE_HOOKUP_OBJECT (WindowUtilisateur, alignment8, "alignment8");
  GLADE_HOOKUP_OBJECT (WindowUtilisateur, hbox8, "hbox8");
  GLADE_HOOKUP_OBJECT (WindowUtilisateur, image13, "image13");
  GLADE_HOOKUP_OBJECT (WindowUtilisateur, label23, "label23");
  GLADE_HOOKUP_OBJECT (WindowUtilisateur, buttonGestiondesequipements, "buttonGestiondesequipements");

  return WindowUtilisateur;
}

GtkWidget*
create_WindowOuvrier (void)
{
  GtkWidget *WindowOuvrier;
  GtkWidget *fixed8;
  GtkWidget *entryuserouvrier;
  GtkWidget *label24;
  GtkWidget *label26;
  GtkWidget *buttonQuitouvrier;
  GtkWidget *alignment14;
  GtkWidget *hbox14;
  GtkWidget *image25;
  GtkWidget *label60;
  GtkWidget *buttonmarquer;
  GtkWidget *alignment9;
  GtkWidget *hbox9;
  GtkWidget *image15;
  GtkWidget *label27;
  GtkWidget *labelmarquer;
  GtkWidget *label25;
  GtkWidget *entrypasswordouvrier;
  GtkWidget *label61;
  GtkWidget *comboboxentryouvrier;
  GtkWidget *image14;
  GtkWidget *failmarquer;

  WindowOuvrier = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (WindowOuvrier), _("WindowOuvrier"));

  fixed8 = gtk_fixed_new ();
  gtk_widget_show (fixed8);
  gtk_container_add (GTK_CONTAINER (WindowOuvrier), fixed8);

  entryuserouvrier = gtk_entry_new ();
  gtk_widget_show (entryuserouvrier);
  gtk_fixed_put (GTK_FIXED (fixed8), entryuserouvrier, 592, 112);
  gtk_widget_set_size_request (entryuserouvrier, 184, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryuserouvrier), 8226);

  label24 = gtk_label_new (_("USERNAME :"));
  gtk_widget_show (label24);
  gtk_fixed_put (GTK_FIXED (fixed8), label24, 472, 112);
  gtk_widget_set_size_request (label24, 120, 24);

  label26 = gtk_label_new_with_mnemonic (_("<span foreground=\"red\"><b>MARQUER VOTRE ABSENCE/PR\303\211SENCE</b></span>"));
  gtk_widget_show (label26);
  gtk_fixed_put (GTK_FIXED (fixed8), label26, 464, 40);
  gtk_widget_set_size_request (label26, 344, 41);
  gtk_label_set_use_markup (GTK_LABEL (label26), TRUE);

  buttonQuitouvrier = gtk_button_new ();
  gtk_widget_show (buttonQuitouvrier);
  gtk_fixed_put (GTK_FIXED (fixed8), buttonQuitouvrier, 744, 8);
  gtk_widget_set_size_request (buttonQuitouvrier, 90, 29);

  alignment14 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment14);
  gtk_container_add (GTK_CONTAINER (buttonQuitouvrier), alignment14);

  hbox14 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox14);
  gtk_container_add (GTK_CONTAINER (alignment14), hbox14);

  image25 = gtk_image_new_from_stock ("gtk-quit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image25);
  gtk_box_pack_start (GTK_BOX (hbox14), image25, FALSE, FALSE, 0);

  label60 = gtk_label_new_with_mnemonic (_("Quitter"));
  gtk_widget_show (label60);
  gtk_box_pack_start (GTK_BOX (hbox14), label60, FALSE, FALSE, 0);

  buttonmarquer = gtk_button_new ();
  gtk_widget_show (buttonmarquer);
  gtk_fixed_put (GTK_FIXED (fixed8), buttonmarquer, 624, 264);
  gtk_widget_set_size_request (buttonmarquer, 112, 29);

  alignment9 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment9);
  gtk_container_add (GTK_CONTAINER (buttonmarquer), alignment9);

  hbox9 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox9);
  gtk_container_add (GTK_CONTAINER (alignment9), hbox9);

  image15 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image15);
  gtk_box_pack_start (GTK_BOX (hbox9), image15, FALSE, FALSE, 0);

  label27 = gtk_label_new_with_mnemonic (_("Marquer"));
  gtk_widget_show (label27);
  gtk_box_pack_start (GTK_BOX (hbox9), label27, FALSE, FALSE, 0);

  labelmarquer = gtk_label_new_with_mnemonic (_("<span foreground=\"green\"><b>Bien marqu\303\251!</b></span>\n"));
  gtk_fixed_put (GTK_FIXED (fixed8), labelmarquer, 712, 304);
  gtk_widget_set_size_request (labelmarquer, 121, 41);
  gtk_label_set_use_markup (GTK_LABEL (labelmarquer), TRUE);

  label25 = gtk_label_new (_("ABSENCE/PR\303\211SENCE :"));
  gtk_widget_show (label25);
  gtk_fixed_put (GTK_FIXED (fixed8), label25, 424, 216);
  gtk_widget_set_size_request (label25, 176, 25);

  entrypasswordouvrier = gtk_entry_new ();
  gtk_widget_show (entrypasswordouvrier);
  gtk_fixed_put (GTK_FIXED (fixed8), entrypasswordouvrier, 592, 160);
  gtk_widget_set_size_request (entrypasswordouvrier, 184, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entrypasswordouvrier), 8226);

  label61 = gtk_label_new (_("PASSWORD :"));
  gtk_widget_show (label61);
  gtk_fixed_put (GTK_FIXED (fixed8), label61, 464, 160);
  gtk_widget_set_size_request (label61, 128, 32);

  comboboxentryouvrier = gtk_combo_box_entry_new_text ();
  gtk_widget_show (comboboxentryouvrier);
  gtk_fixed_put (GTK_FIXED (fixed8), comboboxentryouvrier, 592, 216);
  gtk_widget_set_size_request (comboboxentryouvrier, 189, 29);
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryouvrier), _("Pr\303\251sent(e)"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryouvrier), _("Absent(e)"));

  image14 = create_pixmap (WindowOuvrier, "512x512bb.jpeg");
  gtk_widget_show (image14);
  gtk_fixed_put (GTK_FIXED (fixed8), image14, 0, 0);
  gtk_widget_set_size_request (image14, 416, 384);

  failmarquer = gtk_label_new_with_mnemonic (_("<span foreground=\"red\"><b>V\303\251rifiez votre username ou password !</b></span>"));
  gtk_fixed_put (GTK_FIXED (fixed8), failmarquer, 432, 304);
  gtk_widget_set_size_request (failmarquer, 280, 25);
  gtk_label_set_use_markup (GTK_LABEL (failmarquer), TRUE);

  g_signal_connect ((gpointer) buttonQuitouvrier, "clicked",
                    G_CALLBACK (on_buttonQuitouvrier_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonmarquer, "clicked",
                    G_CALLBACK (on_buttonmarquer_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (WindowOuvrier, WindowOuvrier, "WindowOuvrier");
  GLADE_HOOKUP_OBJECT (WindowOuvrier, fixed8, "fixed8");
  GLADE_HOOKUP_OBJECT (WindowOuvrier, entryuserouvrier, "entryuserouvrier");
  GLADE_HOOKUP_OBJECT (WindowOuvrier, label24, "label24");
  GLADE_HOOKUP_OBJECT (WindowOuvrier, label26, "label26");
  GLADE_HOOKUP_OBJECT (WindowOuvrier, buttonQuitouvrier, "buttonQuitouvrier");
  GLADE_HOOKUP_OBJECT (WindowOuvrier, alignment14, "alignment14");
  GLADE_HOOKUP_OBJECT (WindowOuvrier, hbox14, "hbox14");
  GLADE_HOOKUP_OBJECT (WindowOuvrier, image25, "image25");
  GLADE_HOOKUP_OBJECT (WindowOuvrier, label60, "label60");
  GLADE_HOOKUP_OBJECT (WindowOuvrier, buttonmarquer, "buttonmarquer");
  GLADE_HOOKUP_OBJECT (WindowOuvrier, alignment9, "alignment9");
  GLADE_HOOKUP_OBJECT (WindowOuvrier, hbox9, "hbox9");
  GLADE_HOOKUP_OBJECT (WindowOuvrier, image15, "image15");
  GLADE_HOOKUP_OBJECT (WindowOuvrier, label27, "label27");
  GLADE_HOOKUP_OBJECT (WindowOuvrier, labelmarquer, "labelmarquer");
  GLADE_HOOKUP_OBJECT (WindowOuvrier, label25, "label25");
  GLADE_HOOKUP_OBJECT (WindowOuvrier, entrypasswordouvrier, "entrypasswordouvrier");
  GLADE_HOOKUP_OBJECT (WindowOuvrier, label61, "label61");
  GLADE_HOOKUP_OBJECT (WindowOuvrier, comboboxentryouvrier, "comboboxentryouvrier");
  GLADE_HOOKUP_OBJECT (WindowOuvrier, image14, "image14");
  GLADE_HOOKUP_OBJECT (WindowOuvrier, failmarquer, "failmarquer");

  return WindowOuvrier;
}

