/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <gtk/gtk.h>

#include "interface.h"
#include "support.h"

int
main (int argc, char *argv[])
{
  GtkWidget *WindowWelcome;
  GtkWidget *WindowInscription;
  GtkWidget *WindowConnexion;
  GtkWidget *WindowProprietaire;
  GtkWidget *WindowGestiondesutilisateurs;
  GtkWidget *WindowUtilisateur;
  GtkWidget *WindowOuvrier;

#ifdef ENABLE_NLS
  bindtextdomain (GETTEXT_PACKAGE, PACKAGE_LOCALE_DIR);
  bind_textdomain_codeset (GETTEXT_PACKAGE, "UTF-8");
  textdomain (GETTEXT_PACKAGE);
#endif

  gtk_set_locale ();
  gtk_init (&argc, &argv);

  add_pixmap_directory (PACKAGE_DATA_DIR "/" PACKAGE "/pixmaps");

  /*
   * The following code was added by Glade to create one of each component
   * (except popup menus), just so that you see something after building
   * the project. Delete any components that you don't want shown initially.
   */
  WindowWelcome = create_WindowWelcome ();
  gtk_widget_show (WindowWelcome);
  /*WindowInscription = create_WindowInscription ();
  gtk_widget_show (WindowInscription);
  WindowConnexion = create_WindowConnexion ();
  gtk_widget_show (WindowConnexion);
  WindowProprietaire = create_WindowProprietaire ();
  gtk_widget_show (WindowProprietaire);
  WindowGestiondesutilisateurs = create_WindowGestiondesutilisateurs ();
  gtk_widget_show (WindowGestiondesutilisateurs);
  WindowUtilisateur = create_WindowUtilisateur ();
  gtk_widget_show (WindowUtilisateur);
  WindowOuvrier = create_WindowOuvrier ();
  gtk_widget_show (WindowOuvrier);*/

  gtk_main ();
  return 0;
}

